// Drill library — expanded
// role: warmup | main | cooldown
// intensity: low | medium | medium-high | high
// equipment: wall | ball-machine | partner | none
// tags: solo | partner

const DRILLS = [
  // ───── WARM-UP (8) ─────
  { id: 'w1', name: 'Slow Cross-Court Dink Rally', category: 'warmup', role: 'warmup',
    description: 'Soft cross-court dinks at low pace. Contact in front of body, soft hands. Rally only — no winners.',
    duration: 5, intensity: 'low', equipment: ['partner','wall'], tags: ['solo','partner'],
    notes: '30 in a row both wings before stopping.' },
  { id: 'w2', name: 'Mini-Tennis at Transition Line', category: 'warmup', role: 'warmup',
    description: 'Both players at the transition line. Soft groundstrokes back and forth, controlled bounce.',
    duration: 5, intensity: 'low', equipment: ['partner'], tags: ['partner'],
    notes: 'Loosens arm and reinforces controlled contact.' },
  { id: 'w3', name: 'Self-Feed Volley Pat-a-Cake', category: 'warmup', role: 'warmup',
    description: '4 ft from wall. Continuous soft volleys at chest height, no bounce. Alternate FH/BH every 5 hits.',
    duration: 4, intensity: 'low', equipment: ['wall'], tags: ['solo'],
    notes: 'Loose grip, paddle out front.' },
  { id: 'w4', name: 'Shadow Footwork', category: 'warmup', role: 'warmup',
    description: 'No ball. Split-step, side-shuffle, kitchen-corner pivot, recover. Light pace, full range.',
    duration: 4, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Wakes up footwork.' },
  { id: 'w5', name: 'Paddle Juggling', category: 'warmup', role: 'warmup',
    description: 'Bounce ball on paddle face. 50 alternating FH/BH paddle face. Then 25 on edge.',
    duration: 3, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Feel and touch primer.' },
  { id: 'w6', name: 'Bounce-Catch Progression', category: 'warmup', role: 'warmup',
    description: 'Self-bounce, catch with paddle face (no swing). 10 each side. Then bounce + soft tap into wall.',
    duration: 3, intensity: 'low', equipment: ['wall','none'], tags: ['solo'],
    notes: 'Builds the soft hands you want for resets.' },
  { id: 'w7', name: 'Forehand-Only Rally', category: 'warmup', role: 'warmup',
    description: 'Rally with partner from baseline using FH only. No targets, just clean contact and depth.',
    duration: 4, intensity: 'low', equipment: ['partner'], tags: ['partner'],
    notes: 'Wakes up dominant side.' },
  { id: 'w8', name: 'Dynamic Mobility', category: 'warmup', role: 'warmup',
    description: 'Leg swings, lunges with rotation, shoulder rolls, wrist circles, ankle circles. 30 sec each.',
    duration: 4, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'No ball. Pure prep.' },

  // ───── DINKING (16) ─────
  { id: 'dk1', name: 'Cross-Court Dink Targets', category: 'dinking', role: 'main',
    description: 'Tape two boxes in opposite kitchen corners. Rally cross-court, both aiming for the box.',
    duration: 10, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Most cross-court dinks should be deep + wide.' },
  { id: 'dk2', name: 'Straight Dink Rally', category: 'dinking', role: 'main',
    description: 'Rally dinks straight up the line. Tighter window forces clean contact. Switch sides halfway.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Harder than cross-court because of the shorter window.' },
  { id: 'dk3', name: 'Dink → Speed-Up → Reset', category: 'dinking', role: 'main',
    description: 'Rally dinks. One player randomly speeds up. Other must reset back. Continue.',
    duration: 10, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Best drill for kitchen battles. Hands + decision.' },
  { id: 'dk4', name: 'Figure-8 Dinks', category: 'dinking', role: 'main',
    description: 'One player hits all cross-court; other all straight. Ball traces figure-8.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Switch roles halfway.' },
  { id: 'dk5', name: 'Wall Dink Control', category: 'dinking', role: 'main',
    description: 'Tape 34-inch line on wall. Self-bounce feed, dink so ball lands just over the line. Catch, repeat.',
    duration: 8, intensity: 'low', equipment: ['wall'], tags: ['solo'],
    notes: '30 each wing.' },
  { id: 'dk6', name: 'Topspin Roll Targets', category: 'dinking', role: 'main',
    description: 'Strip on wall 34-40 in. Self-feed low ball, brush low-to-high topspin into strip.',
    duration: 10, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: '30 FH + 30 BH. Your attackable-ball weapon.' },
  { id: 'dk7', name: 'Backhand Cross-Court Dink', category: 'dinking', role: 'main',
    description: 'Both players BH-only, rally cross-court. Forces backhand consistency under repetition.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'BH dinks are where most players leak points.' },
  { id: 'dk8', name: 'Random Direction Dink', category: 'dinking', role: 'main',
    description: 'Partner calls "cross" or "line" right before contact. You execute. Speeds up read + reaction.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'No telegraphing. Hands must be late-prep.' },
  { id: 'dk9', name: 'Triangle Dink Pattern', category: 'dinking', role: 'main',
    description: '3 cones in opponent kitchen (2 corners, 1 middle). Hit dinks rotating through pattern. Track misses.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Builds spatial precision.' },
  { id: 'dk10', name: 'One-Foot Dink Balance', category: 'dinking', role: 'main',
    description: 'Cross-court dink rally with partner. Stand on one foot the entire rally. Switch feet halfway.',
    duration: 6, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Forces upper-body quiet, no leg push.' },
  { id: 'dk11', name: 'Dink Plus Counter', category: 'dinking', role: 'main',
    description: 'Dink, dink, partner speeds up, you counter at their feet. 6-shot pattern. Reset and repeat.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Trains counter accuracy under controlled tempo.' },
  { id: 'dk12', name: 'Defensive Dink Off Body', category: 'dinking', role: 'main',
    description: 'Partner attacks at chest/shoulder. You absorb and dink-block back into kitchen.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Paddle out front, soft grip, no swing.' },
  { id: 'dk13', name: 'Slow-to-Fast Dink Ramp', category: 'dinking', role: 'main',
    description: 'Start slow rally, every 4 shots increase pace slightly. See who breaks first.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Builds tolerance for tempo changes.' },
  { id: 'dk14', name: '4-Corner Dink Accuracy', category: 'dinking', role: 'main',
    description: '4 small targets in opponent kitchen (corners). Self-feed off wall, hit one target per dink in sequence.',
    duration: 8, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: '10 cycles = 40 dinks.' },
  { id: 'dk15', name: 'Dink With Side Shuffle', category: 'dinking', role: 'main',
    description: 'Cross-court dink rally. After each dink, take a side step. Forces movement + balance + soft hands.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Real points have movement; static dinking misses that.' },
  { id: 'dk16', name: 'Shake-and-Bake Dink', category: 'dinking', role: 'main',
    description: 'Mix in occasional short dink (just over net) into a deep dink pattern. Forces partner to step in.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Pull them forward, then attack their next shot.' },

  // ───── THIRD SHOT (10) ─────
  { id: 'th1', name: 'Third Shot Drop Reps', category: 'third-shot', role: 'main',
    description: 'Ball machine or partner feeds returns to baseline. You drop into kitchen corners. Reset, repeat.',
    duration: 12, intensity: 'medium', equipment: ['partner','ball-machine'], tags: ['solo','partner'],
    notes: 'Pace over arc.' },
  { id: 'th2', name: 'Third Shot Drive Reps', category: 'third-shot', role: 'main',
    description: 'Ball machine or partner feeds returns. Drive low and hard at opponent\'s hip/chest. Track first-strike conversion.',
    duration: 10, intensity: 'medium-high', equipment: ['partner','ball-machine'], tags: ['solo','partner'],
    notes: '1-2 paddle-widths above the net.' },
  { id: 'th3', name: 'Third + Fifth Shot Read', category: 'third-shot', role: 'main',
    description: 'Partner returns. You hit 3rd. Partner hits 5th (block, dink, attack). You read and respond.',
    duration: 12, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: '4.5 differentiator: 3rd shot choice based on read.' },
  { id: 'th4', name: 'Drop vs Drive Decision', category: 'third-shot', role: 'main',
    description: 'Partner varies return depth/height. Shallow → drive. Deep low → drop. Call choice out loud.',
    duration: 10, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Speak the decision to wire it in.' },
  { id: 'th5', name: 'Third From Forehand Corner', category: 'third-shot', role: 'main',
    description: 'Start in deep FH corner. Partner serves to deep BH. You move and hit 3rd shot drop cross-court.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Movement + 3rd in one rep.' },
  { id: 'th6', name: 'Third From Backhand Corner', category: 'third-shot', role: 'main',
    description: 'Start deep BH corner. Drop cross-court using backhand. Hardest version.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'If you can do this, your weak side is gone.' },
  { id: 'th7', name: 'Drive Cross vs Line', category: 'third-shot', role: 'main',
    description: 'Partner feeds. Alternate drives: cross-court, then down-the-line. Track placement accuracy.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Drives down-the-line are the surprise weapon.' },
  { id: 'th8', name: 'Drive At Body', category: 'third-shot', role: 'main',
    description: 'Partner returns deep. Drive at their hip or paddle-side shoulder. Most uncomfortable target.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Body shots jam opponents and cause weak returns.' },
  { id: 'th9', name: 'Crash and Burn', category: 'third-shot', role: 'main',
    description: 'Drive 3rd, then sprint to kitchen, split-step. Partner attacks; you reset or counter.',
    duration: 10, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Trains the move you actually make after a drive.' },
  { id: 'th10', name: 'Third Under Fatigue', category: 'third-shot', role: 'main',
    description: '10 jumping jacks, then ball machine or partner feeds 5 returns. Drop or drive each. Repeat 3 sets.',
    duration: 8, intensity: 'high', equipment: ['partner','ball-machine'], tags: ['solo','partner'],
    notes: 'You play tournaments tired. Practice tired.' },

  // ───── RESET (10) ─────
  { id: 'rs1', name: 'Reset Ladder', category: 'reset', role: 'main',
    description: '7 ft from wall. Drive hard, reset rebound soft into taped box at net height. 20 in a row each wing.',
    duration: 10, intensity: 'medium-high', equipment: ['wall'], tags: ['solo'],
    notes: 'Absorb-then-soften under speed.' },
  { id: 'rs2', name: 'Reaction Reset', category: 'reset', role: 'main',
    description: '5 ft from wall. Drive hard, soft-block rebound, repeat without losing ball. Track max streak.',
    duration: 6, intensity: 'high', equipment: ['wall'], tags: ['solo'],
    notes: 'Hand-speed + grip pressure.' },
  { id: 'rs3', name: 'Two-Paddle Reset', category: 'reset', role: 'main',
    description: 'Partner attacks at chest/hip from kitchen. You stand at transition line, reset every ball into kitchen.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Loose grip, paddle out front.' },
  { id: 'rs4', name: 'Reset From Transition Zone', category: 'reset', role: 'main',
    description: 'Start baseline. Partner feeds 5th ball you reset. Move forward 2 steps. Repeat until at kitchen.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'The 4.0→4.5 leak: getting through no-man\'s-land.' },
  { id: 'rs5', name: 'Catch and Cradle', category: 'reset', role: 'main',
    description: 'Partner attacks. You "catch" the ball with paddle face open and angled, dropping it into kitchen.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Imagine catching an egg.' },
  { id: 'rs6', name: 'Off-Body Reset', category: 'reset', role: 'main',
    description: 'Partner attacks at your body. Use BH paddle face (chicken-wing position) to absorb and reset.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Body shots are the hardest to reset. Drill the specific position.' },
  { id: 'rs7', name: 'Shoulder-High Reset', category: 'reset', role: 'main',
    description: 'Partner attacks balls aimed at your shoulder. Reset down into kitchen without overhitting.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'High balls tempt you to attack. Resist.' },
  { id: 'rs8', name: 'Forehand-Only Reset', category: 'reset', role: 'main',
    description: 'Partner attacks all to your FH side. You reset every one. Builds confidence on dominant side.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Foundation before mixing wings.' },
  { id: 'rs9', name: 'Backhand-Only Reset', category: 'reset', role: 'main',
    description: 'Partner attacks all to your BH side. Reset only with backhand.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Usually the weaker reset wing.' },
  { id: 'rs10', name: 'Reset Then Counter', category: 'reset', role: 'main',
    description: 'Partner attacks. You reset. Partner dinks. You attack the dink (if attackable). 4-shot pattern.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Defense → offense transition. Don\'t stay passive after a reset.' },

  // ───── TRANSITION (8) ─────
  { id: 'tr1', name: 'No-Man\'s-Land Volley/Dink', category: 'transition', role: 'main',
    description: 'You at transition line. Partner at kitchen. Mix of volleys at chest and half-volleys off short hops.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Bend knees, paddle out front.' },
  { id: 'tr2', name: 'Forward Progression', category: 'transition', role: 'main',
    description: 'Start baseline. Each reset, move forward 2 steps. Reach kitchen in 4 shots without popping up.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Models real-point progression.' },
  { id: 'tr3', name: 'Split-Step Recovery', category: 'transition', role: 'main',
    description: 'Move forward 2 steps, split-step, react to partner\'s feed, reset, repeat. Continuous.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Split before every ball.' },
  { id: 'tr4', name: 'Drop and Follow', category: 'transition', role: 'main',
    description: 'Hit 3rd shot drop from baseline, then move forward to NVZ split-stepping every 2 steps.',
    duration: 8, intensity: 'medium-high', equipment: ['partner','ball-machine'], tags: ['solo','partner'],
    notes: 'The "approach" most rec players never practice.' },
  { id: 'tr5', name: 'Half-Volley Forehand', category: 'transition', role: 'main',
    description: 'Ball machine or partner feeds short bounces at your FH side. Half-volley back into their court.',
    duration: 6, intensity: 'medium-high', equipment: ['partner','ball-machine'], tags: ['solo','partner'],
    notes: 'Soft hands, low paddle, lift through contact.' },
  { id: 'tr6', name: 'Half-Volley Backhand', category: 'transition', role: 'main',
    description: 'Same but BH side. Tougher because of swing geometry.',
    duration: 6, intensity: 'medium-high', equipment: ['partner','ball-machine'], tags: ['solo','partner'],
    notes: 'Continental grip, no wrist flip.' },
  { id: 'tr7', name: 'Transition Reset Chain', category: 'transition', role: 'main',
    description: 'Partner attacks repeatedly. You reset each, then advance one step. 5-step progression.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Multiple resets before reaching NVZ.' },
  { id: 'tr8', name: 'Crossover Step Drill', category: 'transition', role: 'main',
    description: 'In transition zone, partner feeds wide. Crossover step + half-volley back. Both directions.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Real points have lateral pulls, not just forward movement.' },

  // ───── VOLLEY (11) ─────
  { id: 'v1', name: 'Two-Ball Volley Loop', category: 'volley', role: 'main',
    description: 'Continuous wall volleys at chest height, no bounce. 50 FH → 50 BH → 50 alternating.',
    duration: 8, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: 'Hand speed, balance, paddle quietness.' },
  { id: 'v2', name: 'Punch Volley Targets', category: 'volley', role: 'main',
    description: 'Tape two boxes on wall: knee and shoulder. Punch volleys alternating into each target.',
    duration: 8, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: 'Short, compact swing. No backswing.' },
  { id: 'v3', name: 'Volley Counter-Attack', category: 'volley', role: 'main',
    description: 'Partner speeds up at hip/chest. Counter-volley to their feet or shoulder. Live to 6 shots.',
    duration: 10, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Aim down. Counter at the source.' },
  { id: 'v4', name: 'Backhand Punch Volley', category: 'volley', role: 'main',
    description: 'Wall. BH-only volleys, paddle face slightly open, short punch. 30 in a row chest height.',
    duration: 6, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: 'BH volley is usually weaker at kitchen.' },
  { id: 'v5', name: 'Forehand Volley Targets', category: 'volley', role: 'main',
    description: 'Wall. FH-only volleys to alternating targets (low + high). 30 reps.',
    duration: 6, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: 'Even your strong wing needs targeted reps.' },
  { id: 'v6', name: 'Block Volley', category: 'volley', role: 'main',
    description: 'Partner speeds up hard. You block (no swing, paddle face open, absorb). Ball drops into kitchen.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Best defense to a hard speedup.' },
  { id: 'v7', name: 'Drop Volley', category: 'volley', role: 'main',
    description: 'Partner dinks. You drop-volley (touch volley) into their kitchen with no pace. 10 each side.',
    duration: 6, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Soft grip. Paddle face does the work.' },
  { id: 'v8', name: 'Punch Volley Deep', category: 'volley', role: 'main',
    description: 'Partner pops up a dink. You punch volley deep at their feet near baseline. 10 reps.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'The "kill" volley when given a high ball.' },
  { id: 'v9', name: 'Volley Exchange', category: 'volley', role: 'main',
    description: 'Both at kitchen. Continuous volleys, no bounce. See how long you can sustain. Mix pace.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Fast-twitch builder. Stay loose.' },
  { id: 'v10', name: 'Volley Plus Recover', category: 'volley', role: 'main',
    description: 'Hit volley, take one step laterally, hit next volley from new position. Continuous with partner.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Footwork between volleys.' },
  { id: 'v11', name: 'Reaction Volley', category: 'volley', role: 'main',
    description: 'Stand 5 ft from wall. Drive hard, eyes closed for 0.5 sec, eyes open, volley return. Reps.',
    duration: 5, intensity: 'high', equipment: ['wall'], tags: ['solo'],
    notes: 'Forces reaction over anticipation.' },

  // ───── ATP / ERNE (6) ─────
  { id: 'ae1', name: 'Erne Footwork', category: 'atp-erne', role: 'main',
    description: 'Kitchen-corner stance at wall. Balls skim parallel to wall. Outside foot lands first past line, plant, punch.',
    duration: 6, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: '20 each side. Footwork legality matters more than swing.' },
  { id: 'ae2', name: 'ATP Setup', category: 'atp-erne', role: 'main',
    description: 'Partner dinks deep + wide cross-court. When ball travels outside post line, you swing around post.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'No need to clear net — only land in court.' },
  { id: 'ae3', name: 'Erne Read Fakes', category: 'atp-erne', role: 'main',
    description: 'Partner dinks cross-court. You fake Erne every 3rd ball. Real Erne when ball is within 12 in of net.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Fakes open the middle. Reads are the real skill.' },
  { id: 'ae4', name: 'Backhand ATP', category: 'atp-erne', role: 'main',
    description: 'Partner pulls you wide on BH side. ATP using backhand swing around post. 10 attempts.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'BH ATP is rarer but devastating.' },
  { id: 'ae5', name: 'Erne Off Straight Dink', category: 'atp-erne', role: 'main',
    description: 'Partner dinks straight up the line near your sideline. Step around for Erne. Land outside line.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Less common Erne path. Drills the read.' },
  { id: 'ae6', name: 'Berne (Backhand Erne)', category: 'atp-erne', role: 'main',
    description: 'Partner dinks crosscourt to your BH. Step around kitchen on BH side and BH-punch the ball down.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Berne = backhand Erne. Same legality rules.' },

  // ───── SERVE & RETURN (11) ─────
  { id: 'sr1', name: 'Deep Serve Target', category: 'serve-return', role: 'main',
    description: 'Tape strip across last 3 ft of service box. Serve aiming for strip. Track in/out.',
    duration: 8, intensity: 'low', equipment: ['wall','none'], tags: ['solo'],
    notes: 'Depth > pace. 30 reps each side.' },
  { id: 'sr2', name: 'Heavy Spin Serve', category: 'serve-return', role: 'main',
    description: 'Topspin and slice serves. Brush up-out for topspin, down-across for slice. Watch the kick.',
    duration: 8, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Variety > max RPM.' },
  { id: 'sr3', name: 'Return Depth Drill', category: 'serve-return', role: 'main',
    description: 'Tape back 3 ft of baseline. Partner serves; return for strip. Track percentage in zone.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Deep return = time to get to kitchen.' },
  { id: 'sr4', name: 'Return + Recover', category: 'serve-return', role: 'main',
    description: 'Return deep, sprint to kitchen, split-step. Partner third-shots; you take it. Repeat.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Whole return-side sequence in one rep.' },
  { id: 'sr5', name: 'Body Serve', category: 'serve-return', role: 'main',
    description: 'Serve aimed at returner\'s hip/body. Jams them and creates weak returns. 10 each side.',
    duration: 6, intensity: 'low', equipment: ['partner','none'], tags: ['solo','partner'],
    notes: 'Underused weapon.' },
  { id: 'sr6', name: 'Wide Corner Serve', category: 'serve-return', role: 'main',
    description: 'Serve into corner of service box. Pulls returner wide off the court. 10 each side.',
    duration: 6, intensity: 'low', equipment: ['partner','none'], tags: ['solo','partner'],
    notes: 'Opens middle for partner.' },
  { id: 'sr7', name: 'T-Serve', category: 'serve-return', role: 'main',
    description: 'Serve to middle line ("T"). Causes hesitation about which player returns. 10 each side.',
    duration: 6, intensity: 'low', equipment: ['partner','none'], tags: ['solo','partner'],
    notes: 'Doubles-specific tactical serve.' },
  { id: 'sr8', name: 'Lob Serve', category: 'serve-return', role: 'main',
    description: 'Practice a high-arc lob serve that lands deep. Legal but tricky to return cleanly.',
    duration: 5, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Mix in occasionally to keep opponents guessing.' },
  { id: 'sr9', name: 'Return to Backhand', category: 'serve-return', role: 'main',
    description: 'Partner serves. You return deep and aimed at server\'s backhand side. Track placement.',
    duration: 6, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Target weak side from the first ball.' },
  { id: 'sr10', name: 'Chip-and-Charge Return', category: 'serve-return', role: 'main',
    description: 'Slice/chip return short and low, charge to kitchen behind it. Forces fast 3rd from server.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'High-pressure tactic. Use selectively.' },
  { id: 'sr11', name: 'Short Angle Return', category: 'serve-return', role: 'main',
    description: 'Return cross-court at a sharp short angle, pulling server wide. Practice 10 each side.',
    duration: 5, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Hard to do consistently. Surprise variant.' },

  // ───── FOOTWORK (9) ─────
  { id: 'fw1', name: 'Split-Step Reaction', category: 'footwork', role: 'main',
    description: 'Partner or trainer points L/R/up/back randomly. Split-step then 2-step move in that direction. 30 reps.',
    duration: 5, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Foundation of every kitchen exchange.' },
  { id: 'fw2', name: 'Ladder Side-Shuffle', category: 'footwork', role: 'main',
    description: 'Agility ladder or chalk lines. Side-shuffle in/out of boxes. 3 sets each direction.',
    duration: 6, intensity: 'high', equipment: ['none'], tags: ['solo'],
    notes: 'Quick feet, low hips. Don\'t cross feet.' },
  { id: 'fw3', name: 'Kitchen Line Bounce-Step', category: 'footwork', role: 'main',
    description: 'Stand at kitchen line. Bounce-step in place, occasionally shift 1 step L or R. Maintain ready position.',
    duration: 5, intensity: 'medium-high', equipment: ['none'], tags: ['solo'],
    notes: 'Active-feet kitchen stance.' },
  { id: 'fw4', name: 'Diagonal Recover Sprints', category: 'footwork', role: 'main',
    description: 'Start kitchen middle. Sprint diagonally to corner, touch, sprint to kitchen, split. 8 reps each side.',
    duration: 6, intensity: 'high', equipment: ['none'], tags: ['solo'],
    notes: 'Lobs require this exact movement.' },
  { id: 'fw5', name: 'Crossover Step', category: 'footwork', role: 'main',
    description: 'Stand at center kitchen. Crossover step wide L, recover, crossover wide R. 15 each side.',
    duration: 5, intensity: 'high', equipment: ['none'], tags: ['solo'],
    notes: 'For reaching wide dinks without losing balance.' },
  { id: 'fw6', name: '4-Corner Sprint', category: 'footwork', role: 'main',
    description: 'Set 4 cones at court corners. Sprint to each, touch, return to center. Repeat 3 times under pace.',
    duration: 6, intensity: 'high', equipment: ['none'], tags: ['solo'],
    notes: 'Conditioning + court awareness.' },
  { id: 'fw7', name: 'Backpedal and Recover', category: 'footwork', role: 'main',
    description: 'Start at kitchen. Backpedal to baseline on call, then sprint forward, split at kitchen. 8 reps.',
    duration: 5, intensity: 'high', equipment: ['none'], tags: ['solo'],
    notes: 'For tracking lobs without turning your back.' },
  { id: 'fw8', name: 'T-Drill', category: 'footwork', role: 'main',
    description: 'Sprint forward, shuffle right, shuffle left, backpedal — traces a T. 5 reps under pace.',
    duration: 5, intensity: 'high', equipment: ['none'], tags: ['solo'],
    notes: 'Full multi-directional movement.' },
  { id: 'fw9', name: 'Direction Change on Call', category: 'footwork', role: 'main',
    description: 'Jog in place at kitchen. Partner shouts a direction; you sprint 3 steps that way, recover. 20 reps.',
    duration: 5, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Reactive movement, not pre-planned.' },

  // ───── COOL-DOWN (5) ─────
  { id: 'cd1', name: 'Slow Dink Rally', category: 'cooldown', role: 'cooldown',
    description: 'Easy soft dinks, no targets, no pressure. Just touch and feel.',
    duration: 5, intensity: 'low', equipment: ['partner','wall'], tags: ['solo','partner'],
    notes: 'Bring HR down. Finish on clean contact.' },
  { id: 'cd2', name: 'Easy Serves', category: 'cooldown', role: 'cooldown',
    description: '10 relaxed serves at 60% pace. Smooth contact. No tracking.',
    duration: 4, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Finish with the simplest motion in the game.' },
  { id: 'cd3', name: 'Static Stretching', category: 'cooldown', role: 'cooldown',
    description: 'Hip flexors, calves, hamstrings, shoulders, wrists. 30 sec each.',
    duration: 5, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Lateral movement breaks down hips/calves first.' },
  { id: 'cd4', name: 'Walking Recovery', category: 'cooldown', role: 'cooldown',
    description: 'Slow walk around the court perimeter for 5 minutes. Deep breathing.',
    duration: 5, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Active recovery beats sitting down.' },
  { id: 'cd5', name: 'Paddle Touch Cool-Down', category: 'cooldown', role: 'cooldown',
    description: 'Light paddle juggling, soft toss-and-catch, slow ground-bounce rhythm. Quiet hands.',
    duration: 4, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Mind-body downshift before leaving the court.' },
];

const CATEGORIES = [
  { id: 'dinking',      label: 'Dinking' },
  { id: 'third-shot',   label: 'Third Shot' },
  { id: 'reset',        label: 'Reset' },
  { id: 'transition',   label: 'Transition' },
  { id: 'volley',       label: 'Volley' },
  { id: 'atp-erne',     label: 'ATP / Erne' },
  { id: 'serve-return', label: 'Serve & Return' },
  { id: 'footwork',     label: 'Footwork' },
  { id: 'warmup',       label: 'Warm-up' },
  { id: 'cooldown',     label: 'Cool-down' },
];
