// ─────────────────────────────────────────────────────────────
// DRILL LIBRARY
// role:       warmup | main | cooldown
// intensity:  low | medium | medium-high | high
// equipment:  wall | ball-machine | partner | none
// tags:       solo | partner (can be both)
// ─────────────────────────────────────────────────────────────

const DRILLS = [
  // ═══════════════ WARM-UP ═══════════════
  { id: 'w1', name: 'Slow Cross-Court Dink Rally', category: 'warmup', role: 'warmup',
    description: 'Soft cross-court dinks at low pace. Focus on contact in front of body and soft hands. No winners — just rally.',
    duration: 5, intensity: 'low', equipment: ['partner', 'wall'], tags: ['solo', 'partner'],
    notes: 'Goal: 30 in a row both wings before stopping.' },
  { id: 'w2', name: 'Mini-Tennis at Transition Line', category: 'warmup', role: 'warmup',
    description: 'Both players at the transition line. Soft groundstrokes back and forth, controlled bounce.',
    duration: 5, intensity: 'low', equipment: ['partner'], tags: ['partner'],
    notes: 'Loosens arm and reinforces controlled contact.' },
  { id: 'w3', name: 'Self-Feed Volley Pat-a-Cake', category: 'warmup', role: 'warmup',
    description: 'Stand 4 ft from wall. Continuous soft volleys at chest height, no bounce. Alternate FH/BH every 5 hits.',
    duration: 4, intensity: 'low', equipment: ['wall'], tags: ['solo'],
    notes: 'Loose grip, paddle out front.' },
  { id: 'w4', name: 'Shadow Footwork', category: 'warmup', role: 'warmup',
    description: 'No ball. Split-step, side-shuffle, kitchen-corner pivot, recover. Light pace, full range.',
    duration: 4, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Wakes up footwork before drilling.' },
  { id: 'w5', name: 'Wrist & Paddle Pendulums', category: 'warmup', role: 'warmup',
    description: 'Hold paddle, swing wrist in figure-8s, arm circles forward and back. 30 sec each.',
    duration: 3, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Wakes up wrist and forearm before fast hands work.' },
  { id: 'w6', name: 'Soft Serve Warm-up', category: 'warmup', role: 'warmup',
    description: '15 easy serves at 60% pace. Focus on smooth toss and clean contact, not power or placement.',
    duration: 4, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Groove the motion before training begins.' },
  { id: 'w7', name: 'Dynamic Stretch Flow', category: 'warmup', role: 'warmup',
    description: 'Leg swings (front/side), walking lunges, torso twists, ankle circles. 30 sec each.',
    duration: 4, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Hips and shoulders open before any lateral work.' },

  // ═══════════════ DINKING ═══════════════
  { id: 'dk1', name: 'Cross-Court Dink Targets', category: 'dinking', role: 'main',
    description: 'Tape two boxes in opposite kitchen corners. Rally cross-court, both trying to land in the box. Count consecutive box hits.',
    duration: 10, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Most cross-court dinks should be deep + wide, not center.' },
  { id: 'dk2', name: 'Straight Dink Rally', category: 'dinking', role: 'main',
    description: 'Rally dinks straight up the line. Tighter window — forces clean contact. Switch sides halfway.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Harder than cross-court because of the shorter window.' },
  { id: 'dk3', name: 'Dink → Speed-Up → Reset', category: 'dinking', role: 'main',
    description: 'Rally dinks. One player randomly speeds up. Other must reset back into the kitchen. Continue dinking.',
    duration: 10, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'The single best drill for kitchen battles. Trains hands + decision.' },
  { id: 'dk4', name: 'Figure-8 Dinks', category: 'dinking', role: 'main',
    description: 'One player hits all dinks cross-court; other hits all dinks straight. Ball traces a figure-8.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Switch roles halfway. Trains directional control and footwork.' },
  { id: 'dk5', name: 'Wall Dink Control', category: 'dinking', role: 'main',
    description: 'Tape 34-in line on wall. Self-bounce feed, soft dink so the ball lands just over the line and rebounds short. Catch and repeat.',
    duration: 8, intensity: 'low', equipment: ['wall'], tags: ['solo'],
    notes: '30 each wing.' },
  { id: 'dk6', name: 'Topspin Roll Targets', category: 'dinking', role: 'main',
    description: 'Tape strip on wall 34–40 in. Feed yourself a low ball, brush low-to-high topspin roll into the strip. Below = net, above = pop-up.',
    duration: 10, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: '30 FH + 30 BH. Attackable-ball weapon.' },
  { id: 'dk7', name: 'Backhand-Only Dink Rally', category: 'dinking', role: 'main',
    description: 'Rally all dinks with backhand only — no forehand allowed.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Most rec players lean on FH dinks; this fixes that.' },
  { id: 'dk8', name: 'No-Pop-Up Rule', category: 'dinking', role: 'main',
    description: 'Standard dink rally, but any ball that rises above shoulder height ends the point. Trains low contact and absorption.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Track longest rally.' },
  { id: 'dk9', name: 'Volley Dink Only', category: 'dinking', role: 'main',
    description: 'Take every dink out of the air — no bouncing allowed. Forces forward stance and quick paddle.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'The 4.5 dink style. Steals time from opponent.' },
  { id: 'dk10', name: 'Lateral Dink Chase', category: 'dinking', role: 'main',
    description: 'Partner pushes you side-to-side with wide dinks. You must return all to one corner.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Footwork + control combined.' },
  { id: 'dk11', name: 'Push Dink Targets', category: 'dinking', role: 'main',
    description: 'Tape 3 zones in kitchen (T-line, sideline corner, opponent feet). Self-feed and dink to each zone in sequence.',
    duration: 8, intensity: 'low', equipment: ['wall', 'ball-machine'], tags: ['solo'],
    notes: '20 reps per zone.' },
  { id: 'dk12', name: 'Dink and Freeze', category: 'dinking', role: 'main',
    description: 'Rally dinks. No speed-ups allowed for 60 seconds straight. Builds patience under boredom.',
    duration: 6, intensity: 'low', equipment: ['partner'], tags: ['partner'],
    notes: 'Most rec players speed up too early. This breaks the habit.' },
  { id: 'dk13', name: 'Diagonal Dink + Recover', category: 'dinking', role: 'main',
    description: 'Dink wide cross-court, then recover to ready position before next ball. Partner alternates direction.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'No leaning — feet must reset every shot.' },

  // ═══════════════ THIRD SHOT ═══════════════
  { id: 'th1', name: 'Third Shot Drop Reps', category: 'third-shot', role: 'main',
    description: 'Partner feeds returns to baseline. You hit third-shot drops aiming for kitchen corners. Reset and repeat.',
    duration: 12, intensity: 'medium', equipment: ['partner', 'ball-machine'], tags: ['solo', 'partner'],
    notes: 'Pace over arc. Drop should land in kitchen, not float.' },
  { id: 'th2', name: 'Third Shot Drive Reps', category: 'third-shot', role: 'main',
    description: 'Partner feeds returns. Drive low and hard at opponent\'s hip or chest. Track first-strike conversion.',
    duration: 10, intensity: 'medium-high', equipment: ['partner', 'ball-machine'], tags: ['solo', 'partner'],
    notes: 'Aim 1–2 paddle-widths above the net.' },
  { id: 'th3', name: 'Third + Fifth Shot Read', category: 'third-shot', role: 'main',
    description: 'Partner feeds return. You hit 3rd. Partner responds with 5th-ball (block, dink, attack). You read and react. Live to 5 shots.',
    duration: 12, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'The 4.5 differentiator: 3rd shot CHOICE based on read.' },
  { id: 'th4', name: 'Drop vs Drive Decision', category: 'third-shot', role: 'main',
    description: 'Partner varies return depth and height. Shallow/floaty → drive. Deep low → drop. Call your choice out loud.',
    duration: 10, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Speak the decision to wire it in.' },
  { id: 'th5', name: 'Machine Drop Reps', category: 'third-shot', role: 'main',
    description: 'Ball machine set to deep moonball returns. Hit 30 drops in a row, tracking how many land in kitchen.',
    duration: 12, intensity: 'medium', equipment: ['ball-machine'], tags: ['solo'],
    notes: 'Goal: 20/30 in kitchen by end of set.' },
  { id: 'th6', name: 'Backhand Third Drop', category: 'third-shot', role: 'main',
    description: 'Machine or partner feed to backhand. Drop only from BH side. Most players neglect this.',
    duration: 10, intensity: 'medium', equipment: ['partner', 'ball-machine'], tags: ['solo', 'partner'],
    notes: 'Continental grip, push through, low-to-high.' },
  { id: 'th7', name: 'Off-Foot Drop', category: 'third-shot', role: 'main',
    description: 'Feed forces you to hit on the run. Drop while moving forward. Recover before next ball.',
    duration: 8, intensity: 'high', equipment: ['partner', 'ball-machine'], tags: ['solo', 'partner'],
    notes: 'Real-game drop is rarely from a balanced stance.' },
  { id: 'th8', name: 'Drop to Backhand', category: 'third-shot', role: 'main',
    description: 'Practice landing every drop on opponent\'s backhand side. Tape a target there. 15 reps.',
    duration: 8, intensity: 'medium', equipment: ['partner', 'wall'], tags: ['solo', 'partner'],
    notes: 'Backhand drops force backhand returns — usually weaker.' },
  { id: 'th9', name: 'Drive + Crash', category: 'third-shot', role: 'main',
    description: 'Hit drive 3rd, then immediately move to kitchen line for the 5th ball volley.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Drive-and-crash is the 4.0/4.5 staple alternative to drop.' },

  // ═══════════════ RESET ═══════════════
  { id: 'rs1', name: 'Reset Ladder', category: 'reset', role: 'main',
    description: '7 ft from wall. Drive ball hard, reset the rebound soft into a taped box at net height. 20 in a row each wing.',
    duration: 10, intensity: 'medium-high', equipment: ['wall'], tags: ['solo'],
    notes: 'Absorb-then-soften pattern under speed.' },
  { id: 'rs2', name: 'Reaction Reset', category: 'reset', role: 'main',
    description: 'Stand 5 ft from wall. Drive hard, soft-block the rebound, repeat without losing the ball. Track max streak.',
    duration: 6, intensity: 'high', equipment: ['wall'], tags: ['solo'],
    notes: 'Pure hand-speed and grip pressure work.' },
  { id: 'rs3', name: 'Two-Paddle Reset', category: 'reset', role: 'main',
    description: 'Partner at kitchen attacks at your chest/hip. You at transition line must reset every ball into the kitchen.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Truest reset training. Loose grip, paddle out front.' },
  { id: 'rs4', name: 'Reset From Transition Zone', category: 'reset', role: 'main',
    description: 'Start at baseline. Partner feeds 5th ball you must reset. Move forward 2 steps. Repeat until at kitchen.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Trains the most common 4.0→4.5 leak: getting through no-man\'s-land.' },
  { id: 'rs5', name: 'Body Reset Block', category: 'reset', role: 'main',
    description: 'Partner targets your sternum. You absorb with paddle face open, deflect into kitchen. 20 reps each side.',
    duration: 6, intensity: 'high', equipment: ['partner', 'ball-machine'], tags: ['solo', 'partner'],
    notes: 'Sternum balls cause most pop-ups. Paddle face open, not flat.' },
  { id: 'rs6', name: 'Backhand-Only Reset', category: 'reset', role: 'main',
    description: 'Wall or partner sends drives. Reset all on backhand side only. Most players\' weak link.',
    duration: 8, intensity: 'medium-high', equipment: ['wall', 'partner'], tags: ['solo', 'partner'],
    notes: 'BH reset = the difference between defending and losing the point.' },
  { id: 'rs7', name: 'Reset to Target', category: 'reset', role: 'main',
    description: 'Cone in opponent\'s kitchen center. Every reset must land within 2 ft of the cone. Count hits out of 20.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Resetting away from opponent\'s paddle buys time.' },
  { id: 'rs8', name: 'Continuous Reset Chain', category: 'reset', role: 'main',
    description: 'Partner attacks 5 in a row at varying heights/positions. You must reset all 5 successfully. If one fails, restart.',
    duration: 10, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Best reset endurance training.' },

  // ═══════════════ TRANSITION ═══════════════
  { id: 'tr1', name: "No-Man's-Land Volley/Dink", category: 'transition', role: 'main',
    description: 'Stand at transition line. Partner at kitchen. Mix of volleys (chest height) and half-volleys (off short hops).',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Bend knees, get under the ball, paddle out front.' },
  { id: 'tr2', name: 'Forward Progression', category: 'transition', role: 'main',
    description: 'Start at baseline. Each successful reset, take 2 steps forward. Reach kitchen in 4 shots without popping up.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Models real-point progression after a 3rd shot.' },
  { id: 'tr3', name: 'Split-Step Recovery', category: 'transition', role: 'main',
    description: 'Move forward 2 steps → split step → react to partner\'s feed → reset → repeat. Continuous.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Split before every ball.' },
  { id: 'tr4', name: '5-Step Approach', category: 'transition', role: 'main',
    description: 'Practice the 5-step approach from baseline to kitchen after a 3rd shot drop. Mark each stride.',
    duration: 6, intensity: 'medium', equipment: ['none'], tags: ['solo'],
    notes: 'Step → step → split → step → split at kitchen.' },
  { id: 'tr5', name: 'Stop-and-Reset', category: 'transition', role: 'main',
    description: 'Mid-stride, partner feeds attack at your feet. You must stop, plant, reset, then continue forward.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Hardest transition shot — moving-while-resetting.' },
  { id: 'tr6', name: 'Punch-and-Move', category: 'transition', role: 'main',
    description: 'Practice taking a volley OUT of the air from transition, then moving forward 2 steps.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Taking volleys saves time in the transition zone.' },

  // ═══════════════ VOLLEY ═══════════════
  { id: 'v1', name: 'Two-Ball Volley Loop', category: 'volley', role: 'main',
    description: 'Continuous wall volleys at chest height, no bounce. 50 FH → 50 BH → 50 alternating. Progress to single-leg.',
    duration: 8, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: 'Hand speed, balance, paddle quietness.' },
  { id: 'v2', name: 'Punch Volley Targets', category: 'volley', role: 'main',
    description: 'Tape two boxes on wall: knee height and shoulder height. Punch volley alternating into each target.',
    duration: 8, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: 'Short compact swing. No backswing.' },
  { id: 'v3', name: 'Volley Counter-Attack', category: 'volley', role: 'main',
    description: 'Partner speeds up at your hip/chest. Counter-volley back into their feet or shoulder. Live to 6 shots.',
    duration: 10, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Aim down, not flat.' },
  { id: 'v4', name: 'Backhand Punch Volley', category: 'volley', role: 'main',
    description: 'Wall. BH volleys only, paddle face slightly open, short punch. 30 in a row at chest height.',
    duration: 6, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: 'BH volley is usually weaker at the kitchen.' },
  { id: 'v5', name: 'Volley Figure-8', category: 'volley', role: 'main',
    description: 'Wall. Alternate FH-cross / BH-straight in a continuous loop pattern.',
    duration: 6, intensity: 'medium-high', equipment: ['wall'], tags: ['solo'],
    notes: 'Wrist control and quick paddle changes.' },
  { id: 'v6', name: 'Volley Swing-Out (Offensive)', category: 'volley', role: 'main',
    description: 'Partner feeds chest-high attackable. Take it out of the air with a topspin swing volley, low-to-high.',
    duration: 6, intensity: 'medium-high', equipment: ['partner', 'ball-machine'], tags: ['solo', 'partner'],
    notes: 'Risky but devastating. Only on chest+ balls.' },
  { id: 'v7', name: 'Off-Paddle Volley', category: 'volley', role: 'main',
    description: 'Partner attacks balls slightly off your paddle side. Reach and redirect without losing balance.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'The shot 4.0s miss. Body angle, not just hand.' },
  { id: 'v8', name: 'High-Low Volley Exchange', category: 'volley', role: 'main',
    description: 'Partner alternates: one volley high (chest), one low (knee). You match.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Forces knee bend on low ones.' },

  // ═══════════════ ATP / ERNE ═══════════════
  { id: 'ae1', name: 'Erne Footwork', category: 'atp-erne', role: 'main',
    description: 'Kitchen-corner stance at wall. Feed balls skimming parallel to wall. Outside foot lands first past line, plant, punch down.',
    duration: 6, intensity: 'medium', equipment: ['wall'], tags: ['solo'],
    notes: '20 each side. Footwork legality matters more than swing.' },
  { id: 'ae2', name: 'ATP Setup', category: 'atp-erne', role: 'main',
    description: 'Partner dinks deep and wide cross-court. When ball travels outside post line, swing low-to-high around the post.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'No need to clear the net — only to land in the court.' },
  { id: 'ae3', name: 'Erne Read Fakes', category: 'atp-erne', role: 'main',
    description: 'Partner dinks crosscourt. Fake an Erne every 3rd ball (lean hard, don\'t go). Real Erne when within 12 in of net.',
    duration: 6, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Fakes open the middle.' },
  { id: 'ae4', name: 'ATP from Machine', category: 'atp-erne', role: 'main',
    description: 'Set machine to deliver wide cross-court dinks. Practice ATP swing with topspin around the post.',
    duration: 10, intensity: 'medium-high', equipment: ['ball-machine'], tags: ['solo'],
    notes: '30 swings. Repeatable reps you can\'t get with a partner.' },
  { id: 'ae5', name: 'Erne Jump Variant', category: 'atp-erne', role: 'main',
    description: 'Two-foot jump from inside the line, land outside, punch down. Higher risk, faster ball.',
    duration: 6, intensity: 'high', equipment: ['wall', 'partner'], tags: ['solo', 'partner'],
    notes: 'Land outside kitchen before contact. Common foot-fault spot.' },
  { id: 'ae6', name: 'ATP Topspin Wrap', category: 'atp-erne', role: 'main',
    description: 'Wide cross-court feed. Heavy topspin wrap-around shot at post height. Brushes hard up the back of the ball.',
    duration: 8, intensity: 'high', equipment: ['ball-machine', 'partner'], tags: ['solo', 'partner'],
    notes: 'Topspin is what makes ATP clear and dip.' },

  // ═══════════════ SERVE & RETURN ═══════════════
  { id: 'sr1', name: 'Deep Serve Target', category: 'serve-return', role: 'main',
    description: 'Tape strip across back 3 ft of service box. Serve aiming for the strip. Track in/out.',
    duration: 8, intensity: 'low', equipment: ['wall', 'none'], tags: ['solo'],
    notes: 'Depth > pace. 30 reps each side.' },
  { id: 'sr2', name: 'Heavy Spin Serve', category: 'serve-return', role: 'main',
    description: 'Topspin and slice serves. Brush up-and-out for topspin; brush down-and-across for slice.',
    duration: 8, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Variety matters more than max RPM.' },
  { id: 'sr3', name: 'Return Depth Drill', category: 'serve-return', role: 'main',
    description: 'Tape back 3 ft of baseline. Partner serves; you return aiming for the strip. Track percentage in zone.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Deep return = time to get to the kitchen.' },
  { id: 'sr4', name: 'Return + Recover', category: 'serve-return', role: 'main',
    description: 'Return serve deep, then sprint to kitchen line and split-step. Partner third-shots; you take it.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Whole return-side sequence in one rep.' },
  { id: 'sr5', name: 'Serve to Backhand', category: 'serve-return', role: 'main',
    description: 'Aim every serve at opponent\'s backhand corner. Tape it; track 10 in a row.',
    duration: 6, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'BH return is usually shorter — sets up your drop.' },
  { id: 'sr6', name: 'Serve Placement Zones', category: 'serve-return', role: 'main',
    description: 'Three zones: T (middle), body, wide. Serve 10 to each. Track hit rate.',
    duration: 10, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Placement variety beats raw pace.' },
  { id: 'sr7', name: 'Spin Variety Sequence', category: 'serve-return', role: 'main',
    description: 'Serve sequence: topspin → slice → flat → repeat. Track which broke best for the opponent.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Mixing spin disrupts return rhythm.' },
  { id: 'sr8', name: 'Return at Opponent Feet', category: 'serve-return', role: 'main',
    description: 'Instead of deep return, low at feet. Forces tough half-volley 3rd. 15 reps each side.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Neutralizes hard servers.' },
  { id: 'sr9', name: 'Return + Drive Third', category: 'serve-return', role: 'main',
    description: 'Return short low. Partner drops third. You drive 5th hard at their feet.',
    duration: 8, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Punish weak drops.' },
  { id: 'sr10', name: 'Lob Return', category: 'serve-return', role: 'main',
    description: 'Lob return high and deep, forcing opponent back. 10 reps. Risky but useful as a wrinkle.',
    duration: 5, intensity: 'low', equipment: ['none', 'partner'], tags: ['solo', 'partner'],
    notes: 'Don\'t use too often — having it makes opponent guess.' },

  // ═══════════════ FOOTWORK ═══════════════
  { id: 'fw1', name: 'Split-Step Reaction', category: 'footwork', role: 'main',
    description: 'Partner points left/right/up/back randomly. Split-step then move 2 steps in that direction. 30 reps.',
    duration: 5, intensity: 'high', equipment: ['none', 'partner'], tags: ['solo', 'partner'],
    notes: 'Foundation of every kitchen exchange.' },
  { id: 'fw2', name: 'Ladder Side-Shuffle', category: 'footwork', role: 'main',
    description: 'Agility ladder or chalk lines. Side-shuffle in/out of boxes. 3 sets each direction.',
    duration: 6, intensity: 'high', equipment: ['none'], tags: ['solo'],
    notes: 'Quick feet, low hips. Don\'t cross feet.' },
  { id: 'fw3', name: 'Kitchen Line Bounce-Step', category: 'footwork', role: 'main',
    description: 'Stand at kitchen line. Bounce-step in place, occasionally shifting 1 step left or right. Maintain ready position.',
    duration: 5, intensity: 'medium-high', equipment: ['none'], tags: ['solo'],
    notes: 'Active-feet kitchen stance.' },
  { id: 'fw4', name: 'Diagonal Recover Sprints', category: 'footwork', role: 'main',
    description: 'Start at kitchen middle. Sprint diagonally to corner, touch, sprint forward to kitchen, split. 8 each side.',
    duration: 6, intensity: 'high', equipment: ['none'], tags: ['solo'],
    notes: 'Lob recovery footwork.' },
  { id: 'fw5', name: 'Z-Pattern Court', category: 'footwork', role: 'main',
    description: 'Touch baseline corner → kitchen opposite corner → baseline opposite corner → kitchen near corner. 4 sets.',
    duration: 6, intensity: 'high', equipment: ['none'], tags: ['solo'],
    notes: 'Court-coverage simulation.' },
  { id: 'fw6', name: 'Backpedal Recovery', category: 'footwork', role: 'main',
    description: 'From kitchen, backpedal 3 steps (lob coverage), pivot, return to kitchen, split-step. 10 reps.',
    duration: 5, intensity: 'high', equipment: ['none'], tags: ['solo'],
    notes: 'Crossover step on the pivot — don\'t turn your back.' },
  { id: 'fw7', name: 'Paddle-Tap Shuffle', category: 'footwork', role: 'main',
    description: 'Lateral shuffle 5 steps, tap paddle to ground each step. Reverse.',
    duration: 5, intensity: 'medium-high', equipment: ['none'], tags: ['solo'],
    notes: 'Forces low hips while moving.' },
  { id: 'fw8', name: 'Cone Agility Weave', category: 'footwork', role: 'main',
    description: '5 cones in a line, 3 ft apart. Weave forward, backward, side-to-side. 3 sets each pattern.',
    duration: 6, intensity: 'high', equipment: ['none'], tags: ['solo'],
    notes: 'General agility builder.' },
  { id: 'fw9', name: '4-Corner Ghost Drill', category: 'footwork', role: 'main',
    description: 'Stand at kitchen middle. Touch 4 court corners (your side) in random order called by partner.',
    duration: 6, intensity: 'high', equipment: ['partner'], tags: ['partner'],
    notes: 'Reaction + court coverage.' },

  // ═══════════════ DOUBLES TACTICS ═══════════════
  { id: 'db1', name: 'Stack-Set Practice', category: 'doubles', role: 'main',
    description: 'With partner, practice full-stack setup off serve: server lines up on left, partner outside court right, switch at contact.',
    duration: 8, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Goal: clean switch in under 2 seconds.' },
  { id: 'db2', name: 'Switch on Third', category: 'doubles', role: 'main',
    description: 'Drop third on cross-court side. Partner crosses behind to cover the line. Call: "switch!"',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Common 4.0/4.5 doubles pattern.' },
  { id: 'db3', name: 'Poach Off Return', category: 'doubles', role: 'main',
    description: 'Partner returns serve. You at kitchen poach the 3rd shot when it floats. Reset position after.',
    duration: 8, intensity: 'medium-high', equipment: ['partner'], tags: ['partner'],
    notes: 'Only commit when ball is clearly in your strike zone.' },
  { id: 'db4', name: 'Fake Poach', category: 'doubles', role: 'main',
    description: 'Lean and bluff a poach motion, then recover. Forces opponent to hit away from middle.',
    duration: 6, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Sprinkle in. Predictable fakes get exploited.' },
  { id: 'db5', name: 'Hand Signals Drill', category: 'doubles', role: 'main',
    description: 'Practice pre-serve hand signals: poach (closed fist), stay (open hand), switch (peace sign). 10 serves with calls.',
    duration: 6, intensity: 'low', equipment: ['partner'], tags: ['partner'],
    notes: 'Signals = communication = won points.' },
  { id: 'db6', name: 'Half-Stack', category: 'doubles', role: 'main',
    description: 'Stack on return side only (not serve). Simpler entry to stacking. 5 return sequences.',
    duration: 6, intensity: 'low', equipment: ['partner'], tags: ['partner'],
    notes: 'Lower-commitment way to keep forehand central.' },
  { id: 'db7', name: 'Middle Ball Communication', category: 'doubles', role: 'main',
    description: 'Partner feeds balls right down the middle. You and partner alternate calling "MINE" or "YOURS". 20 reps.',
    duration: 5, intensity: 'medium', equipment: ['partner'], tags: ['partner'],
    notes: 'Middle balls cause more lost points than weak shots.' },

  // ═══════════════ BALL MACHINE ═══════════════
  { id: 'bm1', name: 'Machine Drop Cycle', category: 'ball-machine', role: 'main',
    description: 'Machine feeds 10 deep returns. Hit drops all 10. Track in-kitchen count. Repeat 3 sets.',
    duration: 12, intensity: 'medium', equipment: ['ball-machine'], tags: ['solo'],
    notes: 'Pure rep count. No partner = no waiting.' },
  { id: 'bm2', name: 'Random-Feed Reaction', category: 'ball-machine', role: 'main',
    description: 'Machine on oscillate mode. React to whatever it feeds. Reset every shot to kitchen.',
    duration: 10, intensity: 'high', equipment: ['ball-machine'], tags: ['solo'],
    notes: 'Unpredictability simulates real play.' },
  { id: 'bm3', name: 'Drive Repetition', category: 'ball-machine', role: 'main',
    description: 'Machine feeds short returns to your strike zone. Drive 30 in a row low and hard.',
    duration: 10, intensity: 'medium-high', equipment: ['ball-machine'], tags: ['solo'],
    notes: 'Grooves drive contact.' },
  { id: 'bm4', name: 'Topspin Roll Reps (Machine)', category: 'ball-machine', role: 'main',
    description: 'Machine on low/medium feed at kitchen height. 40 topspin roll volleys/dinks into opposite kitchen.',
    duration: 12, intensity: 'medium-high', equipment: ['ball-machine'], tags: ['solo'],
    notes: 'Builds attacking dink in volume.' },
  { id: 'bm5', name: 'Side-to-Side Machine', category: 'ball-machine', role: 'main',
    description: 'Machine oscillating wide left/right at kitchen height. Move and dink each. 5 minutes continuous.',
    duration: 8, intensity: 'high', equipment: ['ball-machine'], tags: ['solo'],
    notes: 'Footwork + dink combined.' },
  { id: 'bm6', name: 'Reset Drill (Machine)', category: 'ball-machine', role: 'main',
    description: 'Machine on hard-drive setting. Stand at transition line. Reset 25 in a row into kitchen.',
    duration: 10, intensity: 'high', equipment: ['ball-machine'], tags: ['solo'],
    notes: 'Best reset volume work outside of a partner.' },

  // ═══════════════ COOL-DOWN ═══════════════
  { id: 'cd1', name: 'Slow Dink Rally', category: 'cooldown', role: 'cooldown',
    description: 'Easy soft dinks, no targets, no pressure. Just touch and feel.',
    duration: 5, intensity: 'low', equipment: ['partner', 'wall'], tags: ['solo', 'partner'],
    notes: 'Bring HR down, finish on clean contact.' },
  { id: 'cd2', name: 'Easy Serves', category: 'cooldown', role: 'cooldown',
    description: '10 relaxed serves at 60% pace, focusing on smooth contact. No tracking, no targets.',
    duration: 4, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Finish with the simplest motion in the game.' },
  { id: 'cd3', name: 'Static Stretching', category: 'cooldown', role: 'cooldown',
    description: 'Hip flexors, calves, hamstrings, shoulders, wrists, forearms. 30 sec each.',
    duration: 5, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Lateral movement breaks down hips and calves first.' },
  { id: 'cd4', name: 'Foam Roll Routine', category: 'cooldown', role: 'cooldown',
    description: 'Roll IT bands, quads, calves, glutes, upper back. 30 sec each spot.',
    duration: 6, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Recovery investment.' },
  { id: 'cd5', name: 'Session Notes', category: 'cooldown', role: 'cooldown',
    description: 'Sit and journal: what worked, what didn\'t, one specific thing to focus on next session.',
    duration: 4, intensity: 'low', equipment: ['none'], tags: ['solo'],
    notes: 'Log these in the Log tab. Mental cooldown.' },
];

const CATEGORIES = [
  { id: 'dinking',      label: 'Dinking' },
  { id: 'third-shot',   label: 'Third Shot' },
  { id: 'reset',        label: 'Reset' },
  { id: 'transition',   label: 'Transition' },
  { id: 'volley',       label: 'Volley' },
  { id: 'atp-erne',     label: 'ATP / Erne' },
  { id: 'serve-return', label: 'Serve & Return' },
  { id: 'footwork',     label: 'Footwork' },
  { id: 'doubles',      label: 'Doubles Tactics' },
  { id: 'ball-machine', label: 'Ball Machine' },
  { id: 'warmup',       label: 'Warm-up' },
  { id: 'cooldown',     label: 'Cool-down' },
];

// ─────────────────────────────────────────────────────────────
// ASSESSMENT SKILLS — tiered observable criteria
// ─────────────────────────────────────────────────────────────

const ASSESSMENT_SKILLS = [
  // ─── 3.0 ───
  { id: 'a30_serve',     tier: 3.0, area: 'Serve',         name: 'Consistent serve',
    drill: 'Hit 10 serves in the service box.',           pass: 7, of: 10 },
  { id: 'a30_fh',        tier: 3.0, area: 'Groundstrokes', name: 'Forehand consistency',
    drill: 'Rally 15 forehand groundstrokes from baseline crosscourt; count those landing in singles court.', pass: 10, of: 15 },
  { id: 'a30_bh',        tier: 3.0, area: 'Groundstrokes', name: 'Backhand consistency',
    drill: 'Rally 15 backhand groundstrokes from baseline crosscourt; count those landing in singles court.', pass: 8, of: 15 },
  { id: 'a30_volley',    tier: 3.0, area: 'Volley',        name: 'Volley basics',
    drill: 'From kitchen line, return 15 volleys back over the net.', pass: 10, of: 15 },
  { id: 'a30_dink',      tier: 3.0, area: 'Dink',          name: 'Sustained dink rally',
    drill: 'Count consecutive cross-court dinks landing in kitchen (out of 20 attempts).', pass: 10, of: 20 },
  { id: 'a30_rules',     tier: 3.0, area: 'Knowledge',     name: 'Rules and score-keeping',
    drill: 'Self-rate: can you keep score correctly and call faults accurately? (1 = yes, 0 = no)', pass: 1, of: 1 },

  // ─── 3.5 ───
  { id: 'a35_deepserve', tier: 3.5, area: 'Serve',         name: 'Deep serve placement',
    drill: 'Land 10 serves in the back third of the service box.', pass: 6, of: 10 },
  { id: 'a35_deepreturn',tier: 3.5, area: 'Return',        name: 'Deep return',
    drill: 'Return 10 serves landing in the back third of the court.', pass: 6, of: 10 },
  { id: 'a35_drop',      tier: 3.5, area: 'Third Shot',    name: 'Third shot drop attempts',
    drill: 'Land 15 third shot drops in the kitchen.', pass: 7, of: 15 },
  { id: 'a35_dinkrally', tier: 3.5, area: 'Dink',          name: 'Extended dink rally',
    drill: 'Sustain 20 consecutive cross-court dinks with partner.', pass: 15, of: 20 },
  { id: 'a35_volley',    tier: 3.5, area: 'Volley',        name: 'Controlled volley',
    drill: 'From kitchen, land 15 volleys in opponent kitchen or transition.', pass: 12, of: 15 },
  { id: 'a35_move',      tier: 3.5, area: 'Movement',      name: 'Get to kitchen consistently',
    drill: 'After return, reach kitchen line before partner\'s 3rd shot lands. 10 reps.', pass: 7, of: 10 },

  // ─── 4.0 ───
  { id: 'a40_servevar',  tier: 4.0, area: 'Serve',         name: 'Serve variety',
    drill: 'Hit 3 different serve types (topspin, slice, flat), 10 each. Count total in target.', pass: 21, of: 30 },
  { id: 'a40_drop',      tier: 4.0, area: 'Third Shot',    name: 'Reliable third shot drop',
    drill: 'Land 15 third shot drops in kitchen against medium-deep returns.', pass: 10, of: 15 },
  { id: 'a40_reset',     tier: 4.0, area: 'Reset',         name: 'Reset from transition',
    drill: 'Reset 10 attacks from transition zone into the kitchen.', pass: 8, of: 10 },
  { id: 'a40_roll',      tier: 4.0, area: 'Attack',        name: 'Topspin roll attack',
    drill: '15 topspin rolls off mid-height balls — count those landing as winners or forcing weak returns.', pass: 8, of: 15 },
  { id: 'a40_dinkplace', tier: 4.0, area: 'Dink',          name: 'Dink placement (not just rally)',
    drill: 'Dink to specified zones (deep corner, opponent feet) — 15 reps.', pass: 10, of: 15 },
  { id: 'a40_recognize', tier: 4.0, area: 'Tactics',       name: 'Speed-up vs reset recognition',
    drill: 'In a 10-ball exchange, correctly identify each ball as attack/dink/reset opportunity.', pass: 7, of: 10 },
  { id: 'a40_stack',     tier: 4.0, area: 'Doubles',       name: 'Basic stacking awareness',
    drill: 'Execute one clean stacked serve and one stacked return with partner. (2 max)', pass: 2, of: 2 },

  // ─── 4.5 ───
  { id: 'a45_dropdrive', tier: 4.5, area: 'Third Shot',    name: 'Drop vs drive based on read',
    drill: 'Given 10 varying returns, correctly choose drop or drive AND execute. Coach- or self-rated.', pass: 7, of: 10 },
  { id: 'a45_reset',     tier: 4.5, area: 'Reset',         name: 'Resets under pressure',
    drill: 'Reset 12 hard attacks (chest/hip targets) into the kitchen.', pass: 10, of: 12 },
  { id: 'a45_spinserve', tier: 4.5, area: 'Serve',         name: 'Tournament-grade spin serves',
    drill: 'Hit 10 heavy-spin serves with clear break and deep placement.', pass: 7, of: 10 },
  { id: 'a45_atp',       tier: 4.5, area: 'Attack',        name: 'ATP execution',
    drill: 'When ATP opportunity arises in live play or feed (10 attempts), execute successfully.', pass: 5, of: 10 },
  { id: 'a45_erne',      tier: 4.5, area: 'Attack',        name: 'Erne execution',
    drill: 'When Erne opportunity arises (10 attempts), execute legally and successfully.', pass: 3, of: 10 },
  { id: 'a45_tactical',  tier: 4.5, area: 'Tactics',       name: 'Mid-match tactical adjustment',
    drill: 'In a real match, identify and exploit a specific opponent weakness within first game. (1 = yes)', pass: 1, of: 1 },
  { id: 'a45_hands',     tier: 4.5, area: 'Attack',        name: 'Hand speed in firefights',
    drill: 'In kitchen firefights to 6 shots, win majority of exchanges out of 10.', pass: 6, of: 10 },
  { id: 'a45_doubles',   tier: 4.5, area: 'Doubles',       name: 'Advanced doubles strategy',
    drill: 'Use stacking AND poaching effectively in a real game. Coach-rated. (1 = yes)', pass: 1, of: 1 },
];

const ASSESSMENT_TIERS = [3.0, 3.5, 4.0, 4.5];
