// Game-simulation drills — live-point scenarios rather than repetition drills
// Each game has: id, format (doubles/singles), name, category, players, rules, focus, difficulty

const DOUBLES_GAMES = [
  // ───── KITCHEN / NVZ BATTLES ─────
  { id: 'gd-1', format: 'doubles', category: 'kitchen', difficulty: 'medium',
    name: 'Kitchen Battle to 7', players: '2v2',
    focus: 'Hands, resets, speed-up recognition',
    rules: 'Both teams start at the kitchen line. Rally begins with a cross-court dink. Play out the point live. First to 7 wins. Rotate serving side each game.',
    notes: 'Trains full kitchen decision-making: when to dink, when to speed up, when to reset.' },
  { id: 'gd-2', format: 'doubles', category: 'kitchen', difficulty: 'hard',
    name: 'Attack-Defend-Reset Cycle', players: '2v2',
    focus: 'Forced offense-defense oscillation',
    rules: 'Player A attacks (speed-up). Player B resets. Player A dinks. Player B attacks. Player A resets. Continue live until error. Winner: first to 5 successful cycles.',
    notes: 'Wires the pattern real high-level points follow.' },
  { id: 'gd-3', format: 'doubles', category: 'kitchen', difficulty: 'hard',
    name: 'Two-vs-One Kitchen', players: '2v1',
    focus: 'Hand speed, resets under fire',
    rules: 'Two players at kitchen dink and attack; one player defends alone at the kitchen. Defender must survive to 15 rally shots. Rotate every 2 min.',
    notes: 'Builds hand speed and resets under sustained pressure.' },
  { id: 'gd-4', format: 'doubles', category: 'kitchen', difficulty: 'medium',
    name: 'Mid-Point Handoff', players: '2v2',
    focus: 'Dink-to-attack transition',
    rules: 'Rally starts with dinks at kitchen. First 6 shots must be dinks. After that, either team can speed up anytime. Live to end of point. First to 7.',
    notes: 'Simulates realistic tempo shifts vs. pre-agreed attack windows.' },
  { id: 'gd-5', format: 'doubles', category: 'kitchen', difficulty: 'medium',
    name: 'No Speed-Up Below Shoulder', players: '2v2',
    focus: 'Ball selection, patience',
    rules: 'Any speed-up on a ball below shoulder height loses the point. Must wait for a truly attackable ball. Play to 11.',
    notes: 'Forces discipline; punishes low-percentage attacks.' },

  // ───── TRANSITION / DROPS ─────
  { id: 'gd-6', format: 'doubles', category: 'transition', difficulty: 'medium',
    name: 'Serve + Return + Third + Fifth Live', players: '2v2',
    focus: 'The 5 shots that decide most points',
    rules: 'Play full points but score only continues if the point lasts through the 5th shot. Server serves, returner returns, server hits 3rd, returner hits 5th. Point continues live if 5th ball is in.',
    notes: 'Highest-leverage sequence in the sport, isolated.' },
  { id: 'gd-7', format: 'doubles', category: 'transition', difficulty: 'hard',
    name: 'Third Shot Choice Under Pressure', players: '2v2',
    focus: 'Reading return quality',
    rules: 'Returner deliberately varies return depth (shuffles between deep/medium/shallow). Server must read and choose drop vs. drive on the fly. Live point after that. Play to 11.',
    notes: 'Trains the read, not just the shot.' },
  { id: 'gd-8', format: 'doubles', category: 'transition', difficulty: 'medium',
    name: 'Approach Line Game', players: '2v2',
    focus: 'Advancing through transition',
    rules: 'Serving team must stay behind the kitchen until their 3rd shot lands in opponent kitchen. Only then can they advance. If drop doesn\'t land in kitchen, they must reset from transition. Play to 11.',
    notes: 'Simulates the earn-your-way-in reality.' },
  { id: 'gd-9', format: 'doubles', category: 'transition', difficulty: 'medium',
    name: 'Two-Bounce Escape', players: '2v2',
    focus: 'Getting through no-man\'s-land',
    rules: 'Serving team cannot volley the 5th, 7th, or 9th shot — must let each bounce. Forces them to earn NVZ position by drops and half-volleys instead of volleys.',
    notes: 'The 4.0→4.5 leak is right here.' },

  // ───── TACTICAL / CONSTRAINT ─────
  { id: 'gd-10', format: 'doubles', category: 'tactical', difficulty: 'medium',
    name: 'Diagonal Cross-Court Only', players: '2v2',
    focus: 'Cross-court patience, sharp angles',
    rules: 'Every shot must land in the diagonally opposite half of the court. Down-the-line shots lose the point. Play to 7.',
    notes: 'Forces cross-court discipline and angle recognition.' },
  { id: 'gd-11', format: 'doubles', category: 'tactical', difficulty: 'medium',
    name: 'No Middle Rule', players: '2v2',
    focus: 'Wide targeting, precision',
    rules: 'Any ball landing in the middle third of the court loses the point. Every shot must go wide left or wide right. Play to 7.',
    notes: 'Opens ATP and Erne opportunities; builds precision.' },
  { id: 'gd-12', format: 'doubles', category: 'tactical', difficulty: 'hard',
    name: 'Backhand Rally Start', players: '2v2',
    focus: 'BH consistency under pressure',
    rules: 'Every dink and volley must be a backhand until the first speed-up. After a speed-up, all shots allowed. Play to 7.',
    notes: 'Exposes weak side; forces improvement.' },
  { id: 'gd-13', format: 'doubles', category: 'tactical', difficulty: 'hard',
    name: 'Every Third Shot Wide', players: '2v2',
    focus: 'Pattern discipline',
    rules: 'Every 3rd shot of a rally must land wide (outside the middle third). Missing the pattern loses the point. Play to 7.',
    notes: 'Wire in patterns rather than reactive shots.' },

  // ───── MOVEMENT / POSITIONING ─────
  { id: 'gd-14', format: 'doubles', category: 'movement', difficulty: 'medium',
    name: 'Lob and Recover', players: '2v2',
    focus: 'Lob defense and tracking',
    rules: 'Either team can lob at any point in the rally. The team lobbed over must chase, recover, and reset the point. Play to 11.',
    notes: 'Most common leak point at 4.0-4.5.' },
  { id: 'gd-15', format: 'doubles', category: 'movement', difficulty: 'medium',
    name: 'Stack and Switch Live', players: '2v2',
    focus: 'Stacking mechanics under pressure',
    rules: 'Both teams must stack every point (agreed side). Observer counts missed switches or blown coverage. Play to 11.',
    notes: 'Practices stacking in real point pressure, not shadow reps.' },
  { id: 'gd-16', format: 'doubles', category: 'movement', difficulty: 'hard',
    name: 'Erne / ATP Bonus', players: '2v2',
    focus: 'Reading Erne/ATP opportunities',
    rules: 'Normal scoring, but any point won with a legal Erne or ATP counts as 2. Play to 11.',
    notes: 'Incentivizes reads that most rec players never look for.' },

  // ───── PRESSURE / ENDGAME ─────
  { id: 'gd-17', format: 'doubles', category: 'pressure', difficulty: 'hard',
    name: 'Sudden Death Deuce', players: '2v2',
    focus: 'Playing under score pressure',
    rules: 'Every point starts at deuce (10-10). Win by 2. Play best of 5 mini-games.',
    notes: 'Trains the actual moments matches turn on.' },
  { id: 'gd-18', format: 'doubles', category: 'pressure', difficulty: 'hard',
    name: 'First to Break', players: '2v2',
    focus: 'Serve-hold consistency',
    rules: 'Servers keep serving until they lose 3 points in a row (a "break"). First team to break 3 times wins.',
    notes: 'Isolates service-side execution.' },
  { id: 'gd-19', format: 'doubles', category: 'pressure', difficulty: 'hard',
    name: 'Down-2 Comeback', players: '2v2',
    focus: 'Playing from behind',
    rules: 'Every game starts at 9-11 (you\'re losing 9-11). You must come back to win 12-11 or better. Best of 3.',
    notes: 'Match nerve, patience, and shot selection when trailing.' },
  { id: 'gd-20', format: 'doubles', category: 'pressure', difficulty: 'medium',
    name: 'Silent Point', players: '2v2',
    focus: 'Reads without communication',
    rules: 'No verbal calls or communication allowed during a point. Must read partner\'s coverage and gaps visually. Play to 11.',
    notes: 'Forces court awareness. Illuminates who\'s been coasting on partner calls.' },

  // ───── DOUBLES PREP (2 PLAYERS) ─────
  { id: 'gd-21', format: 'doubles', category: 'doubles-prep', difficulty: 'medium',
    name: 'Skinny Singles', players: '2p',
    focus: 'Cross-court patterns in tighter space',
    rules: 'Each player uses only their half of the court (both ad or both deuce). Ball must land in the diagonally opposite skinny half. Play out live. First to 11.',
    notes: 'Trains the cross-court dink and drive patterns that dominate real doubles.' },
  { id: 'gd-22', format: 'doubles', category: 'doubles-prep', difficulty: 'medium',
    name: 'Half-Court Doubles Battle', players: '2p',
    focus: 'Doubles rhythm at half the coverage',
    rules: 'Play full doubles rules but on one half of the court only (both use same side — ad or deuce). Serve, return, kitchen rules all apply. First to 11.',
    notes: 'Simulates doubles pressure with just two people; sharpens angle and pace decisions.' },
  { id: 'gd-23', format: 'doubles', category: 'doubles-prep', difficulty: 'medium',
    name: 'Cross-Court Dink Battle', players: '2p',
    focus: 'Most common doubles kitchen exchange',
    rules: 'Both at kitchen line, positioned in the same cross-court corners (e.g., both left-side). Rally cross-court dinks only. Winner: first to force error or attackable ball 7 times.',
    notes: 'The bulk of doubles kitchen play happens right here.' },
  { id: 'gd-24', format: 'doubles', category: 'doubles-prep', difficulty: 'medium',
    name: 'Third Shot Feeder Rotation', players: '2p',
    focus: 'High-volume 3rd shot reps',
    rules: 'Player A serves and hits third shot only (drop or drive). Player B returns each serve deep to allow the read. Ball is dead after 3rd shot. Track drop quality out of 10. Rotate roles.',
    notes: 'The single most important shot in doubles, drilled solo-style with a partner.' },
  { id: 'gd-25', format: 'doubles', category: 'doubles-prep', difficulty: 'hard',
    name: 'Poach Trainer', players: '2p',
    focus: 'Recognizing and executing the poach',
    rules: 'Player A dinks cross-court from kitchen. Player B stands at kitchen middle. B poaches — steps toward middle and cuts off A\'s dink with an Erne or aggressive volley. 10 successful poaches, rotate.',
    notes: 'The move that separates 4.0 from 4.5 in doubles.' },
  { id: 'gd-26', format: 'doubles', category: 'doubles-prep', difficulty: 'medium',
    name: 'Fake Stack Drill', players: '2p',
    focus: 'Stacking footwork without 4 players',
    rules: 'Player A starts on the "wrong" side (as in a stack). After each serve, A moves to their proper side; B moves to cover. Practice the rotation in isolation. 10 stacks, switch roles.',
    notes: 'Wire in stacking movement so live play doesn\'t become chaos.' },
  { id: 'gd-27', format: 'doubles', category: 'doubles-prep', difficulty: 'medium',
    name: 'Middle Ball Priority', players: '2p',
    focus: 'The middle-call habit',
    rules: 'Both players at kitchen, standing as if partners. One player self-feeds balls down the middle. The other must call "mine!" and take each one. Track missed calls. 20 feeds, rotate.',
    notes: 'Middle balls decide more doubles points than any other target.' },
  { id: 'gd-28', format: 'doubles', category: 'doubles-prep', difficulty: 'hard',
    name: 'Kitchen Cross-Fire', players: '2p',
    focus: 'DTL and cross-court shot patterns',
    rules: 'Both at kitchen, cross-court positions. Player A can only hit down-the-line; Player B can only hit cross-court. Rally continuously. Switch roles every 10 shots.',
    notes: 'Forces both wing patterns and builds tolerance for tight windows.' },
  { id: 'gd-29', format: 'doubles', category: 'doubles-prep', difficulty: 'hard',
    name: 'Shake and Bake Practice', players: '2p',
    focus: 'Drive + crash combination',
    rules: 'Player A serves and hits third shot drive. Player B, imagining they\'re the crashing partner, moves forward and hits a putaway volley on the 4th shot. Rotate every 10 attempts.',
    notes: 'The most punishing doubles pattern when executed together.' },
  { id: 'gd-30', format: 'doubles', category: 'doubles-prep', difficulty: 'hard',
    name: 'Setup-Finish Drill', players: '2p',
    focus: 'The two-shot doubles combo',
    rules: 'Player A hits a wide dink or angle that pulls Player B off the kitchen. Player A then plays a putaway into the empty space Player B left. Track successful two-shot combinations. Rotate roles.',
    notes: 'Points are earned in pairs of shots, not single winners.' },
  { id: 'gd-31', format: 'doubles', category: 'doubles-prep', difficulty: 'hard',
    name: 'DTL Attack Trigger', players: '2p',
    focus: 'Reading the DTL attack window',
    rules: 'Both at kitchen, cross-court positions. Rally dinks cross-court. When Player A gets a slightly high ball, they trigger a down-the-line attack. Player B blocks or resets. Play out live.',
    notes: 'The DTL attack is the escape valve from cross-court dink stalemates.' },
  { id: 'gd-32', format: 'doubles', category: 'doubles-prep', difficulty: 'medium',
    name: 'Serve-Return-Third Isolation', players: '2p',
    focus: 'The three shots that decide 60% of doubles points',
    rules: 'Player A serves, Player B returns. Play only 3 shots (serve, return, 3rd). Track quality of return and 3rd shot. Rotate after 10 serves. Do 5 rotations each.',
    notes: 'Isolates the highest-leverage shots without letting the point get away.' },
];

const SINGLES_GAMES = [
  // ───── BASELINE / RALLY CONSTRUCTION ─────
  { id: 'gs-1', format: 'singles', category: 'rally', difficulty: 'medium',
    name: 'Baseline Rally to 10', players: '1v1',
    focus: 'Groundstroke consistency',
    rules: 'Both players stay at baseline. No net approaches. First to 10 rally errors loses.',
    notes: 'Isolates baseline reliability from tactical decisions.' },
  { id: 'gs-2', format: 'singles', category: 'rally', difficulty: 'medium',
    name: 'Cross-Court Only Singles', players: '1v1',
    focus: 'Cross-court angles',
    rules: 'Every shot must land in the diagonally opposite half. Down-the-line loses point. First to 11.',
    notes: 'Forces cross-court discipline and pull-off-court angles.' },
  { id: 'gs-3', format: 'singles', category: 'rally', difficulty: 'medium',
    name: 'Deep-Deep-Approach', players: '1v1',
    focus: 'Rally construction before attacking',
    rules: 'Must hit two consecutive deep balls (past midcourt) before you\'re allowed to approach the net. First to 11.',
    notes: 'Builds patience — most singles points are lost by attacking too early.' },
  { id: 'gs-4', format: 'singles', category: 'rally', difficulty: 'medium',
    name: 'Serve + 3 Live', players: '1v1',
    focus: 'The first three shots',
    rules: 'Every rally scored only if it reaches 3 shots. Server serves, returner returns, server hits 3rd. Live from there.',
    notes: 'Focuses execution on the shots most singles points end on.' },

  // ───── NET PLAY ─────
  { id: 'gs-5', format: 'singles', category: 'net', difficulty: 'hard',
    name: 'Passing Shot Duel', players: '1v1',
    focus: 'Passing shots vs. net player',
    rules: 'One player at net, other at baseline. Baseline player gets 3 passing attempts per rally to end the point. Rotate every 5 minutes.',
    notes: 'Best drill for the pass-vs-lob decision.' },
  { id: 'gs-6', format: 'singles', category: 'net', difficulty: 'medium',
    name: 'Approach and Volley', players: '1v1',
    focus: 'When to approach + finish',
    rules: 'You must approach net after any ball that lands shorter than midcourt. If you don\'t, opponent wins the point. First to 11.',
    notes: 'Forces the approach that most rec singles players skip.' },
  { id: 'gs-7', format: 'singles', category: 'net', difficulty: 'hard',
    name: 'Lob and Recover Singles', players: '1v1',
    focus: 'Lob defense',
    rules: 'Either player can lob during a rally. Recipient must chase, recover, and reset the point. First to 11.',
    notes: 'Lobs win points in singles more than doubles. Both offense and defense matter.' },
  { id: 'gs-8', format: 'singles', category: 'net', difficulty: 'medium',
    name: 'First to Net', players: '1v1',
    focus: 'Racing to attacking position',
    rules: 'Both start at baseline each point. First player to legally reach kitchen line during rally gets +1 bonus point if they win the rally.',
    notes: 'Rewards aggressive approach timing.' },

  // ───── CONSTRAINT ─────
  { id: 'gs-9', format: 'singles', category: 'constraint', difficulty: 'hard',
    name: 'Backhand Only Groundstroke', players: '1v1',
    focus: 'BH consistency',
    rules: 'Must use backhand for every groundstroke from baseline. Volleys can be either wing. First to 7.',
    notes: 'Exposes and rebuilds the BH under real pressure.' },
  { id: 'gs-10', format: 'singles', category: 'constraint', difficulty: 'medium',
    name: 'Wide-Only Winners', players: '1v1',
    focus: 'Court-opening angles',
    rules: 'You can only win the point on a shot that lands in the outer third (wide) of opponent\'s court. Center-third winners don\'t score. First to 7.',
    notes: 'Trains wide angle finishing.' },
  { id: 'gs-11', format: 'singles', category: 'constraint', difficulty: 'medium',
    name: 'No Drop Shots', players: '1v1',
    focus: 'Drives and lobs only',
    rules: 'Drop shots are illegal — every shot must have real pace or be a lob. First to 11.',
    notes: 'Forces topspin drives and lob development.' },
  { id: 'gs-12', format: 'singles', category: 'constraint', difficulty: 'medium',
    name: 'Slice-Only Approach', players: '1v1',
    focus: 'Slice approach shot',
    rules: 'Any approach to net must be a slice (or you must retreat). First to 11.',
    notes: 'Sliced approach = low bounce = weak return; builds volley setup.' },

  // ───── PRESSURE / ENDGAME ─────
  { id: 'gs-13', format: 'singles', category: 'pressure', difficulty: 'hard',
    name: 'Long Point Game', players: '1v1',
    focus: 'Endurance and construction',
    rules: 'Only rallies of 10+ shots count for scoring. Shorter rallies replay. First to 7.',
    notes: 'Builds patience and conditioning simultaneously.' },
  { id: 'gs-14', format: 'singles', category: 'pressure', difficulty: 'hard',
    name: 'Sudden Death Singles', players: '1v1',
    focus: 'Score pressure',
    rules: 'Every point starts at deuce (10-10). Win by 2. Best of 5.',
    notes: 'Every rally is match point pressure.' },
  { id: 'gs-15', format: 'singles', category: 'pressure', difficulty: 'hard',
    name: 'Down-3 Comeback', players: '1v1',
    focus: 'Playing from behind',
    rules: 'Every game starts at 8-11. You must come back. Best of 3.',
    notes: 'Nerve and shot selection when trailing.' },
  { id: 'gs-16', format: 'singles', category: 'pressure', difficulty: 'medium',
    name: 'Three-Serve Rule', players: '1v1',
    focus: 'Big-serve resource management',
    rules: 'You get 3 "power serves" per game where you can go max effort. All other serves must be safe/spin. Pick your moments. First to 11.',
    notes: 'Trains when to use your best weapon.' },

  // ───── PATTERNS ─────
  { id: 'gs-17', format: 'singles', category: 'patterns', difficulty: 'hard',
    name: 'Inside-Out Only', players: '1v1',
    focus: 'Inside-out shots',
    rules: 'All groundstroke winners must be inside-out (running around the BH to hit an FH cross-court). Non-inside-out winners don\'t score. First to 7.',
    notes: 'Forces movement to the FH.' },
  { id: 'gs-18', format: 'singles', category: 'patterns', difficulty: 'medium',
    name: 'Directional Change Bonus', players: '1v1',
    focus: 'Changing rally direction',
    rules: 'Any point won on a rally with 3+ direction changes (cross-line-cross or line-cross-line) counts as 2. First to 11.',
    notes: 'Incentivizes moving opponent rather than trading pace.' },
  { id: 'gs-19', format: 'singles', category: 'patterns', difficulty: 'hard',
    name: 'Two-Ball Attack', players: '1v1',
    focus: 'Attack construction',
    rules: 'You can only end a point with a winner if the previous shot was also aggressive (drive, angle, or approach). No isolated winners. First to 7.',
    notes: 'Wires the "attack the attack" pattern.' },
  { id: 'gs-20', format: 'singles', category: 'patterns', difficulty: 'medium',
    name: 'Blind Serve Pattern', players: '1v1',
    focus: 'Serve + 1 pattern execution',
    rules: 'Before each service point, server declares out loud where they intend to hit the 3rd shot (line, cross, drop). Point counts double if executed as planned. First to 11.',
    notes: 'Trains preplanned patterns rather than reactive play.' },
];

const GAMES_BY_FORMAT = {
  doubles: DOUBLES_GAMES,
  singles: SINGLES_GAMES,
};

const GAME_CATEGORIES = {
  kitchen:      'Kitchen / NVZ Battles',
  transition:   'Transition & Drops',
  tactical:     'Tactical Constraints',
  movement:     'Movement & Positioning',
  pressure:     'Pressure / Endgame',
  'doubles-prep': 'Doubles Prep (2 Players)',
  rally:        'Baseline Rally',
  net:          'Net Play',
  constraint:   'Constraint Games',
  patterns:     'Shot Patterns',
};
