// Skill assessment library — doubles + singles, 10 skills per level (3.0 → 4.5)

const DOUBLES_SKILLS = [
  // ───── 3.0 ─────
  { id: 'd30-1', level: '3.0', category: 'serve',
    name: 'Legal serve in',
    test: 'Hit 10 serves. Count how many land in the correct service box.',
    criteria: '8 of 10 in' },
  { id: 'd30-2', level: '3.0', category: 'return',
    name: 'Return serve in play',
    test: 'Partner serves 10. Count returns landing in court.',
    criteria: '8 of 10 in court' },
  { id: 'd30-3', level: '3.0', category: 'dinking',
    name: 'Cross-court dink rally',
    test: 'Rally cross-court dinks from kitchen line. Longest consecutive streak.',
    criteria: '4+ consecutive in kitchen' },
  { id: 'd30-4', level: '3.0', category: 'groundstroke',
    name: 'Forehand groundstroke with direction',
    test: 'Partner feeds 10. Aim each at a called side.',
    criteria: '5 of 10 hit chosen side' },
  { id: 'd30-5', level: '3.0', category: 'groundstroke',
    name: 'Backhand groundstroke in court',
    test: 'Partner feeds 10 to backhand. Count those landing in court.',
    criteria: '5 of 10 in court' },
  { id: 'd30-6', level: '3.0', category: 'positioning',
    name: 'No kitchen faults',
    test: 'Play one game. Observer tracks foot faults on volleys.',
    criteria: '0–1 foot fault in a game' },
  { id: 'd30-7', level: '3.0', category: 'positioning',
    name: 'Move to kitchen after return',
    test: 'Play receiving side. Observer tracks if you advance to NVZ after each return.',
    criteria: 'Advances on 80%+ of returns' },
  { id: 'd30-8', level: '3.0', category: 'volley',
    name: 'Soft volley control',
    test: 'Partner feeds 5 mid-pace balls at chest. Volley back without overhitting.',
    criteria: '3 of 5 land in court' },
  { id: 'd30-9', level: '3.0', category: 'partner',
    name: 'Partner communication',
    test: 'Play one game. Observer counts verbal calls (yours/mine/out/switch).',
    criteria: '3+ calls in a game' },
  { id: 'd30-10', level: '3.0', category: 'lob',
    name: 'Basic lob with intent',
    test: 'Hit 5 deliberate lobs from kitchen line over partner at NVZ.',
    criteria: '3 of 5 land in court past NVZ' },

  // ───── 3.5 ─────
  { id: 'd35-1', level: '3.5', category: 'third-shot',
    name: 'Third shot drop reaches kitchen',
    test: 'Partner returns 10 serves deep. Drop third shots. Count landing in opponent kitchen.',
    criteria: '5 of 10 in kitchen' },
  { id: 'd35-2', level: '3.5', category: 'dinking',
    name: 'Backhand dink in kitchen',
    test: 'Rally 10 BH dinks. Count clean ones landing in opponent kitchen.',
    criteria: '5 of 10 in kitchen' },
  { id: 'd35-3', level: '3.5', category: 'dinking',
    name: 'Extended dink rally',
    test: 'Rally dinks cooperatively. Longest streak.',
    criteria: '10+ consecutive' },
  { id: 'd35-4', level: '3.5', category: 'return',
    name: 'Deep return placement',
    test: 'Partner serves 10. Aim each return at last 3 ft of baseline.',
    criteria: '5 of 10 in deep strip' },
  { id: 'd35-5', level: '3.5', category: 'reset',
    name: 'Occasional reset of hard ball',
    test: 'Partner attacks 10 from kitchen. Reset soft into kitchen from transition.',
    criteria: '3 of 10 land in their kitchen' },
  { id: 'd35-6', level: '3.5', category: 'serve',
    name: 'Spin serve (topspin or slice)',
    test: 'Hit 10 serves with intentional spin. Visible kick or curve on bounce.',
    criteria: '5 of 10 with clear spin AND in' },
  { id: 'd35-7', level: '3.5', category: 'volley',
    name: 'Directional volley control',
    test: 'Partner feeds 10 at chest. Volley each to called target.',
    criteria: '5 of 10 hit chosen target' },
  { id: 'd35-8', level: '3.5', category: 'tactics',
    name: 'Drop vs drive decision',
    test: 'Partner varies return quality. Call drop or drive out loud before shot.',
    criteria: '3 of 5 correct choice' },
  { id: 'd35-9', level: '3.5', category: 'positioning',
    name: 'Execute basic stacking',
    test: 'Play one game using pre-planned stack. Observer checks missed rotations.',
    criteria: '0–1 stacking errors' },
  { id: 'd35-10', level: '3.5', category: 'attack',
    name: 'Speed-up on attackable ball',
    test: 'Partner offers 5 high dinks above net. Speed each up with topspin or drive.',
    criteria: '3 of 5 attacks stay in' },

  // ───── 4.0 ─────
  { id: 'd40-1', level: '4.0', category: 'third-shot',
    name: 'Consistent third shot drop',
    test: 'Hit 10 third shots after deep return. Count drops landing in kitchen.',
    criteria: '7 of 10 in kitchen' },
  { id: 'd40-2', level: '4.0', category: 'drive',
    name: 'Hard topspin drive in court',
    test: 'Hit 10 topspin drives from baseline at hip/chest. Count low (under 4 ft) and in.',
    criteria: '5 of 10 low and in' },
  { id: 'd40-3', level: '4.0', category: 'reset',
    name: 'Clean reset from transition zone',
    test: 'Partner attacks 10 from kitchen. Reset from no-man\'s-land into their kitchen.',
    criteria: '5 of 10 soft in kitchen' },
  { id: 'd40-4', level: '4.0', category: 'dinking',
    name: 'Topspin roll dink',
    test: 'Hit 10 topspin roll dinks from kitchen. Visible roll, land in kitchen.',
    criteria: '5 of 10 land with topspin' },
  { id: 'd40-5', level: '4.0', category: 'return',
    name: 'Deep backhand return',
    test: 'Partner serves to BH 10 times. Return deep.',
    criteria: '5 of 10 in deep strip' },
  { id: 'd40-6', level: '4.0', category: 'counter',
    name: 'Counter a speed-up at NVZ',
    test: 'Partner speeds up 10 at body. Counter back low or reset.',
    criteria: '4 of 10 counters land below net in court' },
  { id: 'd40-7', level: '4.0', category: 'tactics',
    name: 'Target opponent weakness',
    test: 'Play one game. Observer notes consistent targeting of weaker side.',
    criteria: 'Targets weak side 70%+' },
  { id: 'd40-8', level: '4.0', category: 'serve',
    name: 'Two serve types in a game',
    test: 'Play game using two distinct serves. Both must land 80%+.',
    criteria: 'Both used, both 80%+' },
  { id: 'd40-9', level: '4.0', category: 'positioning',
    name: 'Hold the kitchen under pressure',
    test: 'Play one game. Observer counts unforced retreats from NVZ.',
    criteria: '2 or fewer retreats' },
  { id: 'd40-10', level: '4.0', category: 'tactics',
    name: 'Strategic stacking by matchup',
    test: 'Play one game. Choose to stack based on partner FH side. Observer evaluates.',
    criteria: 'Correct decision + execution' },

  // ───── 4.5 ─────
  { id: 'd45-1', level: '4.5', category: 'erne',
    name: 'Legal Erne in a point',
    test: 'Across a session, count Ernes attempted in live play that land legally for a point.',
    criteria: '1+ successful Erne' },
  { id: 'd45-2', level: '4.5', category: 'atp',
    name: 'ATP execution',
    test: 'Partner sets up 10 wide cross dinks. ATP when ball travels outside post line.',
    criteria: '3 of 10 ATPs in court' },
  { id: 'd45-3', level: '4.5', category: 'drive',
    name: 'Backhand topspin drive',
    test: 'Hit 10 BH drives with topspin from mid-court. Count low and in.',
    criteria: '5 of 10 topspin + in' },
  { id: 'd45-4', level: '4.5', category: 'attack',
    name: 'Flick from low ball',
    test: 'Partner dinks 10 at thigh height. Flick (wrist snap, topspin) into opponent court.',
    criteria: '3 of 10 in, forcing defense' },
  { id: 'd45-5', level: '4.5', category: 'deception',
    name: 'Disguised drop vs drive',
    test: 'Observer watches 10 third shots. Can they predict drop vs drive pre-contact?',
    criteria: 'Observer correct on 4 or fewer of 10' },
  { id: 'd45-6', level: '4.5', category: 'dinking',
    name: 'Win a dink battle by patience',
    test: 'Track points where dink rally goes 15+ shots. Did you win via error or attackable?',
    criteria: 'Win 60%+ of long dink battles' },
  { id: 'd45-7', level: '4.5', category: 'patterns',
    name: 'Serve sets up third shot',
    test: 'Identify planned serve-to-third pattern. Execute over 5 service points.',
    criteria: '3 of 5 patterns play as planned' },
  { id: 'd45-8', level: '4.5', category: 'lob',
    name: 'Offensive lob',
    test: 'Hit 10 offensive lobs from kitchen. Must clear opponent and land in last 5 ft.',
    criteria: '3 of 10 land deep, force backpedal' },
  { id: 'd45-9', level: '4.5', category: 'counter',
    name: 'Counter from below net',
    test: 'Partner speeds at feet 10 times. Reset or counter so point turns neutral or offensive.',
    criteria: '4 of 10 turn point neutral/offensive' },
  { id: 'd45-10', level: '4.5', category: 'tactics',
    name: 'Mid-game strategy adjustment',
    test: 'Play one game. Observer checks if you visibly change patterns after losing 2 in a row.',
    criteria: 'Adjustment observed' },
];

const SINGLES_SKILLS = [
  // ───── 3.0 ─────
  { id: 's30-1', level: '3.0', category: 'serve',
    name: 'Legal serve in',
    test: 'Hit 10 serves. Count those landing in correct service box.',
    criteria: '8 of 10 in' },
  { id: 's30-2', level: '3.0', category: 'return',
    name: 'Return serve in court',
    test: 'Opponent serves 10. Count returns landing in court.',
    criteria: '8 of 10 in court' },
  { id: 's30-3', level: '3.0', category: 'positioning',
    name: 'Recover to center baseline',
    test: 'Play 5 points. Observer checks if you return to baseline center between shots.',
    criteria: 'Recovers on 4 of 5 points' },
  { id: 's30-4', level: '3.0', category: 'coverage',
    name: 'Cover wide forehand',
    test: 'Opponent feeds 5 wide to FH side. Get to ball, return in court.',
    criteria: '3 of 5 returned in court' },
  { id: 's30-5', level: '3.0', category: 'coverage',
    name: 'Cover wide backhand',
    test: 'Opponent feeds 5 wide to BH side. Reach, return in court.',
    criteria: '3 of 5 returned in court' },
  { id: 's30-6', level: '3.0', category: 'groundstroke',
    name: 'Forehand depth',
    test: 'Hit 10 forehand groundstrokes. Count landing past midcourt.',
    criteria: '5 of 10 past midcourt' },
  { id: 's30-7', level: '3.0', category: 'groundstroke',
    name: 'Backhand in court',
    test: 'Hit 10 BH groundstrokes. Count those landing in opponent court.',
    criteria: '5 of 10 in court' },
  { id: 's30-8', level: '3.0', category: 'rally',
    name: 'Sustain 4-shot rally',
    test: 'Try to rally with opponent. Track longest consecutive shots.',
    criteria: '4+ shot rally consistently' },
  { id: 's30-9', level: '3.0', category: 'lob',
    name: 'Basic lob with intent',
    test: 'Hit 5 lobs from baseline aiming deep. Count those landing in court.',
    criteria: '3 of 5 in court' },
  { id: 's30-10', level: '3.0', category: 'movement',
    name: 'Read and chase short ball',
    test: 'Opponent drops 5 short. Move forward, get a paddle on it.',
    criteria: 'Reaches ball on 3 of 5' },

  // ───── 3.5 ─────
  { id: 's35-1', level: '3.5', category: 'return',
    name: 'Deep return placement',
    test: 'Tape last 3 ft of baseline. Opponent serves 10. Return into strip.',
    criteria: '5 of 10 in deep strip' },
  { id: 's35-2', level: '3.5', category: 'rally',
    name: 'Sustain 10-shot rally',
    test: 'Cooperative rally with opponent. Longest sustained streak.',
    criteria: '10+ shots consistently' },
  { id: 's35-3', level: '3.5', category: 'serve',
    name: 'Spin serve',
    test: '10 serves with intentional topspin or slice. Visible kick or curve on bounce.',
    criteria: '5 of 10 spin + in' },
  { id: 's35-4', level: '3.5', category: 'tactics',
    name: 'Move opponent corner-to-corner',
    test: 'In a rally, intentionally alternate FH then BH corners.',
    criteria: 'Successfully alternates 3+ times' },
  { id: 's35-5', level: '3.5', category: 'attack',
    name: 'Recognize attackable ball',
    test: 'Opponent feeds 10 mixed (short/deep/floaty). Identify which 5 are attackable, attack.',
    criteria: 'Correctly identifies 4 of 5' },
  { id: 's35-6', level: '3.5', category: 'drive',
    name: 'Forehand topspin drive',
    test: '10 FH topspin drives from baseline. Count low and deep.',
    criteria: '5 of 10 low + deep' },
  { id: 's35-7', level: '3.5', category: 'defense',
    name: 'Defensive slice from deep',
    test: 'Pulled wide and deep. Slice back deep cross-court. 5 attempts.',
    criteria: '3 of 5 land deep cross' },
  { id: 's35-8', level: '3.5', category: 'net',
    name: 'Approach the net',
    test: 'After hitting an attacking shot, approach net. Track approaches in a game.',
    criteria: 'Approaches 3+ times in a game' },
  { id: 's35-9', level: '3.5', category: 'net',
    name: 'Pass opponent at net',
    test: 'Opponent at NVZ. Hit 10 passing shots. Count those that pass them in.',
    criteria: '5 of 10 pass cleanly' },
  { id: 's35-10', level: '3.5', category: 'lob',
    name: 'Defensive lob keeps you in',
    test: 'Wide and stretched. Hit defensive lob 5 times. Count those that keep you in the point.',
    criteria: '3 of 5 buy recovery time' },

  // ───── 4.0 ─────
  { id: 's40-1', level: '4.0', category: 'serve',
    name: 'Two distinct serves in a match',
    test: 'Play one game using two clearly different serves (topspin + slice, deep + body, etc.).',
    criteria: 'Both used and in 80%+' },
  { id: 's40-2', level: '4.0', category: 'drive',
    name: 'Backhand topspin groundstroke',
    test: 'Hit 10 BH topspin groundstrokes from baseline. Count low and deep.',
    criteria: '5 of 10 low + deep' },
  { id: 's40-3', level: '4.0', category: 'serve',
    name: 'Serve placement (corners + body)',
    test: 'Call corner/body before each of 10 serves. Count those hitting called zone.',
    criteria: '7 of 10 in called zone' },
  { id: 's40-4', level: '4.0', category: 'tactics',
    name: 'Wide drives pull opponent off court',
    test: 'In a rally, hit 5 wide angles that pull opponent past sideline.',
    criteria: '3 of 5 pull off court' },
  { id: 's40-5', level: '4.0', category: 'lob',
    name: 'Offensive lob over attacker',
    test: 'Opponent at NVZ. Hit 10 offensive lobs over them, land deep.',
    criteria: '5 of 10 land in last 5 ft' },
  { id: 's40-6', level: '4.0', category: 'touch',
    name: 'Drop shot from baseline',
    test: '10 drop shots from baseline. Land just over net in opponent kitchen.',
    criteria: '4 of 10 stay in kitchen' },
  { id: 's40-7', level: '4.0', category: 'tactics',
    name: 'Read opponent stance pre-contact',
    test: 'Watch opponent\'s setup. Predict direction (cross/line) before they contact ball. 10 shots.',
    criteria: 'Correct on 7 of 10' },
  { id: 's40-8', level: '4.0', category: 'tactics',
    name: 'Mix pace within a rally',
    test: 'In a rally, deliberately use 3 different paces (slow, medium, hard).',
    criteria: '3 paces used in same point' },
  { id: 's40-9', level: '4.0', category: 'movement',
    name: 'Recover after wide pulls',
    test: 'Opponent feeds 10 wide. Hit ball, recover to center within 2 steps.',
    criteria: 'Recovers on 7 of 10' },
  { id: 's40-10', level: '4.0', category: 'net',
    name: 'Win 50%+ of net approaches',
    test: 'Play one game. Track points won after net approach vs total approaches.',
    criteria: 'Win 50%+ of approaches' },

  // ───── 4.5 ─────
  { id: 's45-1', level: '4.5', category: 'drive',
    name: 'Inside-out forehand',
    test: 'From BH corner, run around BH and hit inside-out FH to opponent BH corner. 10 attempts.',
    criteria: '5 of 10 land in BH corner' },
  { id: 's45-2', level: '4.5', category: 'deception',
    name: 'Disguise pass vs lob',
    test: 'Observer watches setup for 10 passing-shot situations. Can they predict pass vs lob?',
    criteria: 'Observer correct on 4 or fewer of 10' },
  { id: 's45-3', level: '4.5', category: 'patterns',
    name: 'Win rallies via construction',
    test: 'Play 10 long rallies (8+ shots). Track wins via shot construction rather than power.',
    criteria: '5 of 10 won by construction' },
  { id: 's45-4', level: '4.5', category: 'serve',
    name: 'Three or more serve types',
    test: 'In a match, deploy 3+ distinct serves (topspin, slice, body, lob, etc.).',
    criteria: 'All used, all in 75%+' },
  { id: 's45-5', level: '4.5', category: 'drive',
    name: 'Backhand drive winners',
    test: 'Hit 10 BH drives down line or sharp cross. Count outright winners or forced errors.',
    criteria: '4 of 10 produce winners' },
  { id: 's45-6', level: '4.5', category: 'touch',
    name: 'Slice approach shot',
    test: 'Sliced approach shot from midcourt, follow to net. 5 attempts.',
    criteria: '3 of 5 set up easy volley' },
  { id: 's45-7', level: '4.5', category: 'counter',
    name: 'Counter-attack at net rusher',
    test: 'Opponent approaches net 10 times. Counter with pass or lob.',
    criteria: 'Win 5 of 10 of these points' },
  { id: 's45-8', level: '4.5', category: 'endurance',
    name: 'Sustain pace and strategy over a match',
    test: 'Play full match (3 games to 11). Observer checks for strategic and physical fade.',
    criteria: 'Consistent through game 3' },
  { id: 's45-9', level: '4.5', category: 'tactics',
    name: 'Wide cross-court angle',
    test: 'Hit 10 short cross-court angles that pull opponent past sideline AND well wide of court.',
    criteria: '4 of 10 land sharp angle in' },
  { id: 's45-10', level: '4.5', category: 'tactics',
    name: 'Mid-match strategy shift',
    test: 'Play match. Observer checks if you visibly change strategy after losing first game.',
    criteria: 'Visible shift in second game' },
];

const SKILLS_BY_FORMAT = {
  doubles: DOUBLES_SKILLS,
  singles: SINGLES_SKILLS,
};

const LEVELS = ['3.0', '3.5', '4.0', '4.5'];
const PASS_FULL = 1.0;
const PASS_HALF = 0.5;
const PASS_NONE = 0;
const LEVEL_THRESHOLD = 0.80;
const PREREQ_THRESHOLD = 0.90;
