// Skill assessment library — 10 skills per level, 3.0 → 4.5
// Each skill: name, observable test, success criteria, category
// Player marks each as: not-yet, inconsistent, or reliable
// Level determination logic uses "reliable" as pass.

const SKILLS = [
  // ───── 3.0 LOWER INTERMEDIATE ─────
  { id: 'k30-1', level: '3.0', category: 'serve',
    name: 'Legal serve in',
    test: 'Hit 10 serves. Count how many land in the correct service box (no fault, no let-out).',
    criteria: '8 of 10 in' },
  { id: 'k30-2', level: '3.0', category: 'return',
    name: 'Return serve in play',
    test: 'Partner serves 10 times. Count returns that land in the court.',
    criteria: '8 of 10 in court' },
  { id: 'k30-3', level: '3.0', category: 'dinking',
    name: 'Cross-court dink rally',
    test: 'Rally cross-court dinks from kitchen line. Count longest consecutive streak.',
    criteria: '4+ consecutive in kitchen' },
  { id: 'k30-4', level: '3.0', category: 'groundstroke',
    name: 'Forehand groundstroke with direction',
    test: 'Partner feeds 10 mid-court balls. Aim each at a called side (FH or BH side of partner).',
    criteria: '5 of 10 hit chosen side' },
  { id: 'k30-5', level: '3.0', category: 'groundstroke',
    name: 'Backhand groundstroke in court',
    test: 'Partner feeds 10 to your backhand. Count returns that land in their court.',
    criteria: '5 of 10 in court' },
  { id: 'k30-6', level: '3.0', category: 'positioning',
    name: 'No kitchen faults',
    test: 'Play one full game. Observer tracks kitchen-line foot faults on volleys.',
    criteria: '0–1 foot fault in a game' },
  { id: 'k30-7', level: '3.0', category: 'positioning',
    name: 'Move to kitchen after return',
    test: 'Play one game on the receiving side. Observer tracks if player advances to NVZ after each return.',
    criteria: 'Advances on 80%+ of returns' },
  { id: 'k30-8', level: '3.0', category: 'volley',
    name: 'Soft volley control',
    test: 'Partner feeds 5 mid-pace balls at chest. Volley back without overhitting baseline.',
    criteria: '3 of 5 land in court' },
  { id: 'k30-9', level: '3.0', category: 'partner',
    name: 'Partner communication',
    test: 'Play one game with a partner. Observer counts verbal calls (yours/mine/out/switch).',
    criteria: '3+ calls in a game' },
  { id: 'k30-10', level: '3.0', category: 'lob',
    name: 'Basic lob with intent',
    test: 'Hit 5 deliberate lobs from kitchen line over partner at NVZ.',
    criteria: '3 of 5 land in court past NVZ' },

  // ───── 3.5 SOLID INTERMEDIATE ─────
  { id: 'k35-1', level: '3.5', category: 'third-shot',
    name: 'Third shot drop reaches kitchen',
    test: 'Partner returns 10 serves deep. You hit third-shot drops. Count those landing in opponent\'s kitchen.',
    criteria: '5 of 10 land in kitchen' },
  { id: 'k35-2', level: '3.5', category: 'dinking',
    name: 'Backhand dink in kitchen',
    test: 'Rally with partner forcing 10 BH dinks. Count clean BH dinks landing in their kitchen.',
    criteria: '5 of 10 land in kitchen' },
  { id: 'k35-3', level: '3.5', category: 'dinking',
    name: 'Extended dink rally',
    test: 'Rally dinks at kitchen line cooperatively. Track longest streak.',
    criteria: '10+ consecutive' },
  { id: 'k35-4', level: '3.5', category: 'return',
    name: 'Deep return placement',
    test: 'Partner serves 10. Aim each return at last 3 ft of baseline (mark with tape).',
    criteria: '5 of 10 land in strip' },
  { id: 'k35-5', level: '3.5', category: 'reset',
    name: 'Occasional reset of a hard ball',
    test: 'Partner attacks 10 balls from kitchen. You reset (soft into kitchen) from transition zone.',
    criteria: '3 of 10 land in their kitchen' },
  { id: 'k35-6', level: '3.5', category: 'serve',
    name: 'Spin serve (topspin or slice)',
    test: 'Hit 10 serves with intentional spin. Observable kick (topspin) or curve (slice) on bounce.',
    criteria: '5 of 10 show clear spin AND land in' },
  { id: 'k35-7', level: '3.5', category: 'volley',
    name: 'Directional volley control',
    test: 'Partner feeds 10 at chest. Volley each to a called target (left/right of partner).',
    criteria: '5 of 10 hit chosen target' },
  { id: 'k35-8', level: '3.5', category: 'tactics',
    name: 'Drop vs drive decision',
    test: 'Partner varies return quality. Call drop or drive out loud before each shot.',
    criteria: '3 of 5 correct choice (matches the shot quality)' },
  { id: 'k35-9', level: '3.5', category: 'positioning',
    name: 'Execute basic stacking',
    test: 'Play one game using a pre-planned stack. Observer checks for missed rotations.',
    criteria: '0–1 stacking errors in a game' },
  { id: 'k35-10', level: '3.5', category: 'attack',
    name: 'Speed-up on attackable ball',
    test: 'Partner offers 5 high dinks (above net height). Speed each up with topspin or drive.',
    criteria: '3 of 5 attacked stay in court' },

  // ───── 4.0 ADVANCED INTERMEDIATE ─────
  { id: 'k40-1', level: '4.0', category: 'third-shot',
    name: 'Consistent third shot drop',
    test: 'Hit 10 third shots after a deep return. Count drops landing in opponent\'s kitchen.',
    criteria: '7 of 10 land in kitchen' },
  { id: 'k40-2', level: '4.0', category: 'drive',
    name: 'Hard topspin drive in court',
    test: 'Hit 10 topspin drives from baseline aimed at opponent\'s hip/chest. Count those low (under 4 ft over net) and in.',
    criteria: '5 of 10 low and in' },
  { id: 'k40-3', level: '4.0', category: 'reset',
    name: 'Clean reset from transition zone',
    test: 'Partner attacks 10 from kitchen. You reset from no-man\'s-land into their kitchen.',
    criteria: '5 of 10 land soft in kitchen' },
  { id: 'k40-4', level: '4.0', category: 'dinking',
    name: 'Topspin roll dink',
    test: 'Hit 10 topspin roll dinks from kitchen. Count those landing in opponent\'s kitchen with visible roll.',
    criteria: '5 of 10 land in kitchen with topspin' },
  { id: 'k40-5', level: '4.0', category: 'return',
    name: 'Deep backhand return',
    test: 'Partner serves to BH 10 times. Return deep, ideally to last 3 ft.',
    criteria: '5 of 10 in deep strip' },
  { id: 'k40-6', level: '4.0', category: 'counter',
    name: 'Counter a speed-up at NVZ',
    test: 'Partner speeds up 10 balls at your body from kitchen. You counter back low or reset.',
    criteria: '4 of 10 counters land below net height in their court' },
  { id: 'k40-7', level: '4.0', category: 'tactics',
    name: 'Target opponent weakness',
    test: 'Play one game. Observer notes whether player consistently targets weaker side / lower-skill opponent.',
    criteria: 'Targets weak side on 70%+ of opportunities' },
  { id: 'k40-8', level: '4.0', category: 'serve',
    name: 'Two serve types in a game',
    test: 'Play a game using at least two distinct serves (e.g. heavy topspin + slice; flat + lob).',
    criteria: 'Both serves used and both land in 80%+' },
  { id: 'k40-9', level: '4.0', category: 'positioning',
    name: 'Hold the kitchen under pressure',
    test: 'Play one game. Observer counts unforced retreats from NVZ (steps back when not lobbed).',
    criteria: '2 or fewer retreats in a game' },
  { id: 'k40-10', level: '4.0', category: 'tactics',
    name: 'Strategic stacking by matchup',
    test: 'Play one game. Choose to stack or not based on partner FH side. Observer evaluates decision.',
    criteria: 'Correct decision and execution' },

  // ───── 4.5 ADVANCED ─────
  { id: 'k45-1', level: '4.5', category: 'erne',
    name: 'Legal Erne in a point',
    test: 'Across a session, count Ernes attempted in live play that land legally for a point.',
    criteria: '1+ successful Erne in a session' },
  { id: 'k45-2', level: '4.5', category: 'atp',
    name: 'ATP execution',
    test: 'Partner sets up 10 wide cross-court dinks. Hit around the post when ball travels outside post line.',
    criteria: '3 of 10 ATP attempts land in court' },
  { id: 'k45-3', level: '4.5', category: 'drive',
    name: 'Backhand topspin drive',
    test: 'Hit 10 BH drives with topspin from mid-court. Count low and in.',
    criteria: '5 of 10 with visible topspin and in court' },
  { id: 'k45-4', level: '4.5', category: 'attack',
    name: 'Flick from low ball',
    test: 'Partner dinks 10 at thigh height. Flick (wrist snap, topspin) into opponent court.',
    criteria: '3 of 10 flicks stay in and force a defensive response' },
  { id: 'k45-5', level: '4.5', category: 'deception',
    name: 'Disguised drop vs drive',
    test: 'Observer watches 10 third shots. Can they predict drop vs drive before contact?',
    criteria: 'Observer correct on 4 or fewer of 10' },
  { id: 'k45-6', level: '4.5', category: 'dinking',
    name: 'Win a dink battle by patience',
    test: 'Track points where a dink rally goes 15+ shots. Did player win via opponent error or attackable ball?',
    criteria: 'Wins 60%+ of long dink battles' },
  { id: 'k45-7', level: '4.5', category: 'patterns',
    name: 'Serve sets up third shot',
    test: 'Identify a planned serve-to-third pattern. Execute over 5 service points.',
    criteria: '3 of 5 patterns play out as planned' },
  { id: 'k45-8', level: '4.5', category: 'lob',
    name: 'Offensive lob',
    test: 'Hit 10 offensive lobs from kitchen. Must clear opponent and land in last 5 ft.',
    criteria: '3 of 10 land deep, force backpedal' },
  { id: 'k45-9', level: '4.5', category: 'counter',
    name: 'Counter from below net',
    test: 'Partner speeds up at your feet 10 times. Reset or counter so you turn the point neutral or offensive.',
    criteria: '4 of 10 turn the point neutral/offensive' },
  { id: 'k45-10', level: '4.5', category: 'tactics',
    name: 'Mid-game strategy adjustment',
    test: 'Play one game. Observer checks if player visibly changes patterns after losing 2 points in a row.',
    criteria: 'Adjustment observed at least once' },
];

const LEVELS = ['3.0', '3.5', '4.0', '4.5'];

// Skill level determination thresholds
// Player is "at" level X if:
//   - >= 80% reliable at level X
//   - AND >= 90% reliable at all levels below X
// "Inconsistent" counts as 0.5 toward the percentage.
const PASS_FULL = 1.0;       // reliable = 1
const PASS_HALF = 0.5;       // inconsistent = 0.5
const PASS_NONE = 0;         // not-yet = 0
const LEVEL_THRESHOLD = 0.80;
const PREREQ_THRESHOLD = 0.90;
